// 古典文明人物数据 · 共享 (关系网 + 深度页 共用)
const CLASSICAL_PEOPLE=[
// ═══ 中国 ═══
{id:"guanzhong",n:"管仲",e:"Guan Zhong",c:"china",r:"other",d:"前723—前645",b:"齐桓公相国，法家先驱，盐铁国营开创者，九合诸侯，'仓廪实而知礼节'，与鲍叔牙友谊'管鲍之交'流传千古。",rel:[{i:"baoshuya",t:"挚友"},{i:"qihuan",t:"效力"}]},
{id:"baoshuya",n:"鲍叔牙",e:"Bao Shuya",c:"china",r:"other",d:"约前710—前644",b:"管仲的挚友，多次让利举荐管仲，甘居其下，是古代最著名的友谊典范。",rel:[{i:"guanzhong",t:"挚友"},{i:"qihuan",t:"效力"}]},
{id:"qihuan",n:"齐桓公",e:"Duke Huan of Qi",c:"china",r:"ruler",d:"前685—前643在位",b:"春秋第一霸，任用管仲，九合诸侯，尊王攘夷，晚年信奸臣，饿死宫中。",rel:[{i:"guanzhong",t:"重用"}]},
{id:"jinhuan",n:"晋文公",e:"Duke Wen of Jin",c:"china",r:"ruler",d:"前636—前628在位",b:"流亡19年，62岁执政成春秋第二霸，城濮之战以退避三舍击败楚国。",rel:[{i:"qihuan",t:"同时代霸主"}]},
{id:"zichan",n:"子产",e:"Zichan",c:"china",r:"thinker",d:"约前582—前522",b:"郑国执政，铸刑书于铜鼎——中国最早公布成文法律的政治家，孔子极其尊重他。",rel:[{i:"kongzi",t:"被孔子尊重"}]},
{id:"yanzi",n:"晏婴（晏子）",e:"Yanying",c:"china",r:"other",d:"？—前500",b:"齐国大夫，机智外交家，身材矮小才智卓绝，'橘生淮南则为橘，生淮北则为枳'。",rel:[{i:"kongzi",t:"同时代"}]},
{id:"kongzi",n:"孔子",e:"Confucius",c:"china",r:"thinker",d:"前551—前479",b:"儒家创始人，周游列国14年推行仁政，整理六经，仁礼君子思想影响东亚两千年。",rel:[{i:"yanhui",t:"最爱弟子"},{i:"zilu",t:"护卫弟子"},{i:"zigong",t:"富商弟子"},{i:"zengzi",t:"弟子"},{i:"laozi",t:"曾问礼"},{i:"mencius",t:"思想传承"}]},
{id:"laozi",n:"老子",e:"Laozi",c:"china",r:"thinker",d:"约前571—前471",b:"道家创始人，《道德经》五千言，无为自然，孔子曾向其问礼，'如东方神龙'。",rel:[{i:"kongzi",t:"被问礼"},{i:"zhuangzi",t:"思想先驱"}]},
{id:"yanhui",n:"颜回",e:"Yan Hui",c:"china",r:"thinker",d:"前521—前481",b:"孔子最钟爱弟子，贫穷而乐道，'一箪食一瓢饮'，孔子视其最接近仁，早逝令孔子恸哭。",rel:[{i:"kongzi",t:"师傅"}]},
{id:"zilu",n:"子路",e:"Zilu",c:"china",r:"other",d:"前542—前480",b:"孔子忠实护卫，性情直爽武勇，在卫国内乱中战死，死前仍整好冠带从容就义。",rel:[{i:"kongzi",t:"师傅"}]},
{id:"zigong",n:"子贡",e:"Zi Gong",c:"china",r:"other",d:"前520—前456",b:"儒门第一富商外交家，多次外交救鲁，孔子死后守墓六年，儒家传播的关键推手。",rel:[{i:"kongzi",t:"师傅"}]},
{id:"zengzi",n:"曾参",e:"Zengzi",c:"china",r:"thinker",d:"前505—前435",b:"著《大学》《孝经》，以孝道著称，连接孔子与孟子的关键传承链。",rel:[{i:"kongzi",t:"师傅"},{i:"zisi",t:"授业"}]},
{id:"zisi",n:"子思",e:"Zisi",c:"china",r:"thinker",d:"前483—前402",b:"孔子之孙，著《中庸》，连接孔子与孟子的重要桥梁，将儒家形而上学化。",rel:[{i:"kongzi",t:"祖父"},{i:"zengzi",t:"受业"},{i:"mencius",t:"授业"}]},
{id:"mozi",n:"墨子",e:"Mozi",c:"china",r:"thinker",d:"约前480—前390",b:"墨家创始人，兼爱非攻，节用尚贤，亲自参与守城设计，小孔成像最早记录者，儒家最强竞争对手。",rel:[{i:"kongzi",t:"思想对立"}]},
{id:"yangzhu",n:"杨朱",e:"Yang Zhu",c:"china",r:"thinker",d:"约前440—前360",b:"'拔一毛利天下而不为'，极端个人主义，孟子时代'天下言不归杨则归墨'，著作全失。",rel:[{i:"mozi",t:"思想对立"},{i:"mencius",t:"被批判"}]},
{id:"sunzi",n:"孙武",e:"Sun Tzu",c:"china",r:"general",d:"约前544—前496",b:"兵圣，《孙子兵法》十三篇是世界最重要的军事著作，以宫女测试展示纪律。",rel:[{i:"helv",t:"效力"},{i:"wuzixu",t:"同僚"}]},
{id:"helv",n:"吴王阖闾",e:"King Helü",c:"china",r:"ruler",d:"前514—前496在位",b:"吴国雄主，任用孙武和伍子胥，攻破楚都，春秋末年最强势力，被越国击败后伤重而死。",rel:[{i:"sunzi",t:"重用"},{i:"wuzixu",t:"重用"},{i:"goujian",t:"战场对手"}]},
{id:"wuzixu",n:"伍子胥",e:"Wu Zixu",c:"china",r:"general",d:"前559—前484",b:"过昭关一夜白头，辅助阖闾攻破楚都，掘平王墓鞭尸复仇，反对夫差被赐剑，死前嘱托挂眼看越灭吴。",rel:[{i:"helv",t:"效力"},{i:"sunzi",t:"同僚"},{i:"goujian",t:"战场对手"}]},
{id:"goujian",n:"越王勾践",e:"King Goujian",c:"china",r:"ruler",d:"前496—前465在位",b:"会稽之耻后卧薪尝胆20年，灭吴称霸，中国最著名的忍辱复仇典故。",rel:[{i:"fanli",t:"谋臣"},{i:"fucha",t:"最终灭之"}]},
{id:"fucha",n:"吴王夫差",e:"King Fucha",c:"china",r:"ruler",d:"前495—前473在位",b:"不杀勾践，沉迷西施，最终被越国灭亡，用布遮脸自刎，'无颜见伍子胥于地下'。",rel:[{i:"goujian",t:"被灭"},{i:"xishi",t:"迷恋"}]},
{id:"xishi",n:"西施",e:"Xi Shi",c:"china",r:"other",d:"约前506—？",b:"四大美人之首，越国美人被送给夫差，成功迷惑吴王，越国灭吴的关键棋子。",rel:[{i:"fucha",t:"迷惑"},{i:"fanli",t:"传说随其隐退"}]},
{id:"fanli",n:"范蠡",e:"Fan Li",c:"china",r:"other",d:"约前536—前448",b:"越国谋臣，卧薪尝胆参谋者，功成隐退为陶朱公三次致富散尽，被后世商人尊为财神。",rel:[{i:"goujian",t:"辅佐"},{i:"xishi",t:"传说相恋"}]},
{id:"mencius",n:"孟子",e:"Mencius",c:"china",r:"thinker",d:"前372—前289",b:"儒家亚圣，性善论，民本思想（民为贵君为轻），游历各国推行仁政，与梁惠王齐宣王辩论。",rel:[{i:"kongzi",t:"传承"},{i:"zisi",t:"受业"},{i:"xunzi",t:"对立"},{i:"yangzhu",t:"批判"}]},
{id:"zhuangzi",n:"庄子",e:"Zhuangzi",c:"china",r:"thinker",d:"约前369—前286",b:"道家集大成，蝴蝶梦、庖丁解牛、濠梁之辩，反对礼教，追求精神绝对自由。",rel:[{i:"laozi",t:"思想传承"},{i:"huizi",t:"终身辩友"}]},
{id:"huizi",n:"惠子",e:"Hui Shi",c:"china",r:"thinker",d:"约前370—前310",b:"名家代表，庄子终身辩友，惠子死后庄子悲叹'再无对手'，合同异哲学。",rel:[{i:"zhuangzi",t:"辩友"}]},
{id:"gongsunlong",n:"公孙龙",e:"Gongsun Long",c:"china",r:"thinker",d:"约前320—前250",b:"名家代表，'白马非马'论——具体不等于抽象，中国古代最早的概念分析哲学。",rel:[{i:"huizi",t:"同派"}]},
{id:"suqin",n:"苏秦",e:"Su Qin",c:"china",r:"other",d:"约前340—前284",b:"纵横家，身佩六国相印，头悬梁锥刺股，合纵抗秦的设计者，最终以间谍身份死于车裂。",rel:[{i:"zhangyi",t:"同门对立"},{i:"guiguzi",t:"传说受业"}]},
{id:"zhangyi",n:"张仪",e:"Zhang Yi",c:"china",r:"other",d:"约前370—前310",b:"纵横家，秦国相国，连横破合纵，'张仪欺楚'是古代最著名外交欺诈，与苏秦分庭抗礼。",rel:[{i:"suqin",t:"对立"},{i:"guiguzi",t:"传说受业"}]},
{id:"guiguzi",n:"鬼谷子",e:"Guiguzi",c:"china",r:"thinker",d:"战国时期",b:"纵横家鼻祖，传为苏秦张仪孙膑庞涓之师，《鬼谷子》是中国最早的谋略心理学著作。",rel:[{i:"suqin",t:"传说授业"},{i:"zhangyi",t:"传说授业"},{i:"sunbin",t:"传说授业"}]},
{id:"sunbin",n:"孙膑",e:"Sun Bin",c:"china",r:"general",d:"约前382—前316",b:"《孙膑兵法》作者，被庞涓挖膝盖骨，后以围魏救赵、马陵之战报仇杀庞涓。",rel:[{i:"pangjuan",t:"宿仇"},{i:"guiguzi",t:"传说受业"}]},
{id:"pangjuan",n:"庞涓",e:"Pang Juan",c:"china",r:"general",d:"？—前341",b:"魏国将领，嫉妒孙膑陷害致残，马陵之战中伏被乱箭射死，'遂成竖子之名'。",rel:[{i:"sunbin",t:"宿仇"}]},
{id:"shangyang",n:"商鞅",e:"Shang Yang",c:"china",r:"thinker",d:"约前390—前338",b:"法家政治家，两次变法彻底重塑秦国：军功爵、郡县制、连坐法，变法成功后被车裂。",rel:[{i:"qin_xiaogong",t:"效力"},{i:"hanfeizi",t:"思想先驱"},{i:"shenbuhai",t:"同时代法家"}]},
{id:"qin_xiaogong",n:"秦孝公",e:"Duke Xiao of Qin",c:"china",r:"ruler",d:"前361—前338在位",b:"颁布求贤令，全力支持商鞅变法，奠定秦国称霸基础。",rel:[{i:"shangyang",t:"重用"}]},
{id:"shenbuhai",n:"申不害",e:"Shen Buhai",c:"china",r:"thinker",d:"约前385—前337",b:"韩国相国，法家'术'派，强调帝王驾驭臣下的权谋，与商鞅的'法'分庭抗礼。",rel:[{i:"shangyang",t:"同时代法家"},{i:"hanfeizi",t:"思想先驱"}]},
{id:"xunzi",n:"荀子",e:"Xunzi",c:"china",r:"thinker",d:"约前313—前238",b:"儒家荀派，性恶论，礼治为本，制天命而用之，弟子韩非子和李斯发展为法家。",rel:[{i:"mencius",t:"对立"},{i:"hanfeizi",t:"授业"},{i:"lisi",t:"授业"}]},
{id:"hanfeizi",n:"韩非子",e:"Han Fei",c:"china",r:"thinker",d:"约前280—前233",b:"法家集大成，《韩非子》法术势体系，口吃著述精辟，被同学李斯嫉妒害死狱中。",rel:[{i:"xunzi",t:"受业"},{i:"lisi",t:"同学宿仇"},{i:"qin_shihuang",t:"思想影响"}]},
{id:"lisi",n:"李斯",e:"Li Si",c:"china",r:"other",d:"约前284—前208",b:"秦朝丞相，助秦始皇统一六国，主导书同文，焚书坑儒，赵高政变后被腰斩。",rel:[{i:"xunzi",t:"受业"},{i:"hanfeizi",t:"同学"},{i:"qin_shihuang",t:"辅佐"},{i:"zhaoago",t:"同谋变节"}]},
{id:"qin_shihuang",n:"秦始皇",e:"Qin Shi Huang",c:"china",r:"ruler",d:"前259—前210",b:"中国第一个皇帝，灭六国统一天下，书同文车同轨，焚书坑儒，修长城，兵马俑，开创帝制。",rel:[{i:"lisi",t:"重用"},{i:"zhaoago",t:"被利用"},{i:"xiangyu",t:"推翻其制度"}]},
{id:"zhaoago",n:"赵高",e:"Zhao Gao",c:"china",r:"other",d:"？—前207",b:"秦朝最大奸宦，'指鹿为马'测试忠诚，扶植秦二世，杀李斯，最终被子婴所杀。",rel:[{i:"lisi",t:"政治盟友后杀之"},{i:"qin_shihuang",t:"宦官"}]},
{id:"xiangyu",n:"项羽",e:"Xiang Yu",c:"china",r:"general",d:"前232—前202",b:"贵族后裔，破釜沉舟，巨鹿大胜，推翻秦朝的最大军事力量，垓下四面楚歌，乌江自刎。",rel:[{i:"liubang",t:"宿敌"},{i:"fanzheng",t:"谋士"},{i:"qin_shihuang",t:"推翻"}]},
{id:"fanzheng",n:"范增",e:"Fan Zeng",c:"china",r:"other",d:"前277—前204",b:"项羽'亚父'，鸿门宴力主杀刘邦，被离间计逼走，愤然离去背疽而死。",rel:[{i:"xiangyu",t:"辅佐"}]},
{id:"liubang",n:"刘邦",e:"Liu Bang",c:"china",r:"ruler",d:"前247—前195",b:"汉朝开国皇帝，平民出身，善用人才，战胜项羽，休养生息黄老之术治国。",rel:[{i:"xiangyu",t:"宿敌"},{i:"hanxin",t:"重用"},{i:"xiao_he",t:"倚重"},{i:"zhanglianghan",t:"智囊"}]},
{id:"xiao_he",n:"萧何",e:"Xiao He",c:"china",r:"other",d:"约前257—前193",b:"汉初三杰，进咸阳独取律令图书，制定汉朝法律制度，月下追韩信举荐刘邦。",rel:[{i:"liubang",t:"辅佐"},{i:"hanxin",t:"举荐"}]},
{id:"hanxin",n:"韩信",e:"Han Xin",c:"china",r:"general",d:"约前231—前196",b:"汉初军事天才，胯下之辱后拜大将军，背水一战，十面埋伏，兵仙，被吕后杀害。",rel:[{i:"liubang",t:"效力"},{i:"xiao_he",t:"被举荐"},{i:"xiangyu",t:"对阵"},{i:"kuaitong",t:"谋士"},{i:"lvhou",t:"死于其手"}]},
{id:"kuaitong",n:"蒯通",e:"Kuai Tong",c:"china",r:"other",d:"秦末汉初",b:"韩信的谋士、著名说客。曾劝韩信趁势自立、三分天下，'勇略震主者身危，功盖天下者不赏'；韩信念刘邦旧恩不听。后刘邦欲烹之，他以'各为其主'自辩获赦。据《史记·淮阴侯列传》。",rel:[{i:"hanxin",t:"劝其自立"},{i:"liubang",t:"献策获赦"}]},
{id:"zhanglianghan",n:"张良",e:"Zhang Liang",c:"china",r:"other",d:"约前250—前186",b:"汉初三杰，运筹帷幄，鸿门宴化解危机，功成身退学道修仙。",rel:[{i:"liubang",t:"辅佐"}]},
{id:"lvhou",n:"吕后",e:"Empress Lü",c:"china",r:"ruler",d:"前241—前180",b:"中国历史上第一位称制的女性，执政约15年，政治上维持汉初休养生息，将戚夫人制成人彘。",rel:[{i:"liubang",t:"皇后"},{i:"hanxin",t:"诛杀"}]},
{id:"dongzhongshu",n:"董仲舒",e:"Dong Zhongshu",c:"china",r:"thinker",d:"前179—前104",b:"西汉大儒，提出'罢黜百家独尊儒术'，天人感应说，将儒家改造为国家意识形态。",rel:[{i:"wudi_han",t:"效力"},{i:"kongzi",t:"推崇"}]},
{id:"wudi_han",n:"汉武帝",e:"Emperor Wu of Han",c:"china",r:"ruler",d:"前156—前87",b:"西汉最重要皇帝，独尊儒术，推恩令，盐铁专卖，遣卫青霍去病征匈奴，派张骞通西域。",rel:[{i:"dongzhongshu",t:"重用"},{i:"weiqing",t:"重用"},{i:"huoqubing",t:"重用"},{i:"zhangqian",t:"遣使"},{i:"simarqian",t:"宫刑后著史"}]},
{id:"weiqing",n:"卫青",e:"Wei Qing",c:"china",r:"general",d:"约前140—前106",b:"七次出击匈奴，收复河套，大将军，封狼居胥的奠基者，汉武帝舅兄。",rel:[{i:"wudi_han",t:"效力"},{i:"huoqubing",t:"舅甥"}]},
{id:"huoqubing",n:"霍去病",e:"Huo Qubing",c:"china",r:"general",d:"前140—前117",b:"军事天才，两次河西之战，扫荡漠北，17岁出征24岁去世，'匈奴不灭何以家为'。",rel:[{i:"wudi_han",t:"效力"},{i:"weiqing",t:"外甥"}]},
{id:"zhangqian",n:"张骞",e:"Zhang Qian",c:"china",r:"other",d:"约前164—前114",b:"两次出使西域，被匈奴俘虏10年仍不辱使命，实际开通丝绸之路，获封博望侯。",rel:[{i:"wudi_han",t:"奉命"},{i:"liuche",t:"丝路后继者班超"}]},
{id:"simarqian",n:"司马迁",e:"Sima Qian",c:"china",r:"other",d:"约前145—前86",b:"《史记》作者，因为李陵辩护遭宫刑，忍辱完成中国第一部纪传体通史，史家之绝唱。",rel:[{i:"wudi_han",t:"供职被宫刑"}]},
{id:"liuche",n:"班超",e:"Ban Chao",c:"china",r:"general",d:"32—102",b:"以36人在西域纵横30年，恢复汉朝西域控制，派甘英出使大秦（罗马），投笔从戎典故。",rel:[{i:"zhangqian",t:"承张骞所辟丝路"}]},
// ═══ 史记补充（古籍拆解·批次1）═══
{id:"gongziqian",n:"公子虔",e:"Gongzi Qian",c:"china",r:"other",d:"战国·秦",b:"秦国公族，太子驷的师傅。太子犯法，商鞅依新法处他劓刑（割鼻），从此与商鞅结下死仇；二十余年后助新王清算商鞅。据《史记·商君列传》。",rel:[{i:"shangyang",t:"宿仇"},{i:"qin_huiwen",t:"辅佐"}]},
{id:"qin_huiwen",n:"秦惠文王",e:"King Huiwen of Qin",c:"china",r:"ruler",d:"前337—前311在位",b:"名驷，少年为太子时因犯法连累师傅受刑。即位后第一件大事便是车裂商鞅；却又沿用商鞅之法，秦国继续强大——'商鞅虽死，秦法未败'。",rel:[{i:"shangyang",t:"清算"},{i:"qin_xiaogong",t:"继位"},{i:"gongziqian",t:"师傅"}]},
{id:"dongzhongshu",n:"董仲舒",e:"Dong Zhongshu",c:"china",r:"thinker",d:"前179—前104",b:"汉代大儒，向汉武帝进言'罢黜百家，独尊儒术'，从此儒学成为中国两千年的官方思想；'天人感应'学说亦出其手。",rel:[{i:"wudi_han",t:"进言"},{i:"kongzi",t:"尊崇"}]},
{id:"liguang",n:"李广",e:"Li Guang",c:"china",r:"general",d:"？—前119",b:"西汉名将'飞将军'，匈奴闻之丧胆，箭术神乎其神（射石没镞）；却一生难封侯，终因迷路失期、不愿受辱而自刎，'李广难封'成为怀才不遇的千古之叹。",rel:[{i:"wudi_han",t:"效力"},{i:"weiqing",t:"同征匈奴"},{i:"liling",t:"祖父"}]},
{id:"liling",n:"李陵",e:"Li Ling",c:"china",r:"general",d:"？—前74",b:"李广之孙，率五千步兵深入匈奴血战，矢尽援绝被迫投降。汉武帝震怒族其家；唯司马迁为他辩护，反遭宫刑——《史记》正是在这场屈辱之后写成。",rel:[{i:"liguang",t:"孙"},{i:"simarqian",t:"受其辩护"},{i:"wudi_han",t:"获罪"}]},

// ═══ 希腊 ═══
{id:"thales",n:"泰利斯",e:"Thales",c:"greece",r:"thinker",d:"约前624—前546",b:"第一位哲学家，预测前585年日食，'万物本质是水'，从神话到理性解释的第一人。",rel:[{i:"anaximander",t:"学生"}]},
{id:"anaximander",n:"阿纳克西曼德",e:"Anaximander",c:"greece",r:"thinker",d:"约前611—前546",b:"泰利斯学生，宇宙本质是无限者（Apeiron），绘制西方第一张世界地图，早期进化思想。",rel:[{i:"thales",t:"老师"}]},
{id:"pythagoras",n:"毕达哥拉斯",e:"Pythagoras",c:"greece",r:"thinker",d:"约前570—前495",b:"毕达哥拉斯定理，发现音乐与数学的关系，建立神秘主义兄弟会，'万物皆数'。",rel:[{i:"thales",t:"受影响"}]},
{id:"heraclitus",n:"赫拉克利特",e:"Heraclitus",c:"greece",r:"thinker",d:"约前535—前475",b:"'万物流动，无物常住'，'人不能两次踏进同一条河流'，晦涩著称，对立统一的先驱。",rel:[{i:"parmenides",t:"思想对立"}]},
{id:"parmenides",n:"巴门尼德",e:"Parmenides",c:"greece",r:"thinker",d:"约前515—前450",b:"'存在存在，不存在不存在'——变化是幻觉，真实是不变的一，深刻影响柏拉图。",rel:[{i:"heraclitus",t:"思想对立"},{i:"plato",t:"影响"}]},
{id:"democritus",n:"德谟克利特",e:"Democritus",c:"greece",r:"thinker",d:"约前460—前370",b:"原子论创始人，万物由不可分原子组成在空虚中运动——距现代物理学概念2400年。",rel:[{i:"epicurus",t:"思想影响"}]},
{id:"protagoras",n:"普罗塔戈拉",e:"Protagoras",c:"greece",r:"thinker",d:"约前490—前420",b:"智者派领袖，'人是万物的尺度'，西方相对主义宣言，第一个公开收费教学的哲学家。",rel:[{i:"socrates",t:"思想对立"}]},
{id:"solon",n:"梭伦",e:"Solon",c:"greece",r:"ruler",d:"约前638—前558",b:"雅典立法者，废除债务奴隶制，按财富分级公民，奠定民主基础，七贤之一。",rel:[{i:"peisistratos",t:"反对"},{i:"cleisthenes",t:"民主先驱"}]},
{id:"peisistratos",n:"庇西特拉图",e:"Peisistratos",c:"greece",r:"ruler",d:"约前607—前527",b:"雅典僭主，三起三落，推动经济发展，资助戏剧，客观上削弱贵族为民主铺路。",rel:[{i:"solon",t:"后继"},{i:"cleisthenes",t:"对手"}]},
{id:"cleisthenes",n:"克莱斯提尼",e:"Cleisthenes",c:"greece",r:"ruler",d:"约前570—前508",b:"雅典民主之父，废血缘部落，建500人议会，发明贝壳放逐制，真正民主制度建立者。",rel:[{i:"solon",t:"传承"},{i:"peisistratos",t:"对手"},{i:"pericles",t:"民主先驱"}]},
{id:"miltiades",n:"米太亚德",e:"Miltiades",c:"greece",r:"general",d:"前550—前489",b:"马拉松战役（前490年）统帅，两翼包围战术击败波斯，希腊的救星，后遭政治迫害而死。",rel:[{i:"themistocles",t:"前辈"},{i:"darius1",t:"战场对手"}]},
{id:"leonidas",n:"列奥尼达一世",e:"Leonidas I",c:"greece",r:"general",d:"约前540—前480",b:"斯巴达王，温泉关300壮士统帅，明知必死仍阻击波斯三天，西方英雄主义永恒象征。",rel:[{i:"xerxes",t:"战场对手"},{i:"themistocles",t:"盟友"}]},
{id:"themistocles",n:"地米斯托克利",e:"Themistocles",c:"greece",r:"general",d:"约前524—前459",b:"萨拉米斯海战总策划者，以200艘战船以狭窄水道击败波斯巨舰，拯救希腊文明。",rel:[{i:"leonidas",t:"盟友"},{i:"xerxes",t:"战场对手"},{i:"pericles",t:"前辈"}]},
{id:"pericles",n:"伯里克利",e:"Pericles",c:"greece",r:"ruler",d:"约前495—前429",b:"雅典黄金时代领导者，扩大民主，建帕特农神庙，死于雅典大瘟疫。",rel:[{i:"themistocles",t:"继承民主"},{i:"socrates",t:"同时代"},{i:"aspasia",t:"情人"}]},
{id:"aspasia",n:"阿斯帕西娅",e:"Aspasia",c:"greece",r:"other",d:"约前470—前400",b:"伯里克利情人，来自米利都，博学智慧，苏格拉底也向她请教修辞，雅典最著名的女性知识分子。",rel:[{i:"pericles",t:"伴侣"},{i:"socrates",t:"交往"}]},
{id:"aeschylus",n:"埃斯库罗斯",e:"Aeschylus",c:"greece",r:"other",d:"约前525—前456",b:"悲剧之父，《俄瑞斯忒亚》现存最早完整悲剧，参加马拉松战役，墓志铭只提战士身份。",rel:[{i:"sophocles",t:"后继"},{i:"miltiades",t:"同僚"}]},
{id:"sophocles",n:"索福克勒斯",e:"Sophocles",c:"greece",r:"other",d:"约前496—前406",b:"《俄狄浦斯王》——亚里士多德誉为悲剧典范，《安提戈涅》探讨法律与道德，90岁仍创作。",rel:[{i:"aeschylus",t:"传承"},{i:"euripides",t:"同时代"}]},
{id:"euripides",n:"欧里庇得斯",e:"Euripides",c:"greece",r:"other",d:"约前484—前406",b:"《美狄亚》《特洛伊妇女》，最具批判精神，质疑神话和战争，'舞台上的哲学家'。",rel:[{i:"sophocles",t:"同时代"},{i:"socrates",t:"相互欣赏"}]},
{id:"aristophanes",n:"阿里斯托芬",e:"Aristophanes",c:"greece",r:"other",d:"约前446—前386",b:"喜剧之父，《云》讽刺苏格拉底，《利西斯特拉达》——女性以性罢工反战，史上最早反战喜剧。",rel:[{i:"socrates",t:"讽刺"}]},
{id:"herodotus",n:"希罗多德",e:"Herodotus",c:"greece",r:"other",d:"约前484—前425",b:"历史之父，《历史》记录希波战争，游历埃及波斯，将神话与历史混合，奠定西方史学传统。",rel:[{i:"themistocles",t:"记录功绩"}]},
{id:"thucydides",n:"修昔底德",e:"Thucydides",c:"greece",r:"other",d:"约前460—前400",b:"批判性历史之父，《伯罗奔尼撒战争史》，修昔底德陷阱概念来源，因失职被流放20年。",rel:[{i:"pericles",t:"记录演讲"}]},
{id:"socrates",n:"苏格拉底",e:"Socrates",c:"greece",r:"thinker",d:"约前470—前399",b:"雅典哲学奠基人，苏格拉底方法，'我只知道我一无所知'，被判处死刑，从容饮毒芹就义。",rel:[{i:"plato",t:"授业"},{i:"xenophon",t:"弟子"},{i:"alcibiades",t:"崇拜者"},{i:"pericles",t:"同时代"}]},
{id:"xenophon",n:"色诺芬",e:"Xenophon",c:"greece",r:"other",d:"约前430—前354",b:"苏格拉底弟子，历史学家军事家，《长征记》记录希腊雇佣军万里撤退，保存苏格拉底思想。",rel:[{i:"socrates",t:"受业"}]},
{id:"alcibiades",n:"阿尔西比亚德斯",e:"Alcibiades",c:"greece",r:"general",d:"约前450—前404",b:"雅典最有才也最危险的政治家，美貌非凡，策动西西里远征惨败，先叛斯巴达再叛波斯。",rel:[{i:"socrates",t:"崇拜师傅"},{i:"pericles",t:"监护人"}]},
{id:"plato",n:"柏拉图",e:"Plato",c:"greece",r:"thinker",d:"约前427—前347",b:"理念论，建立雅典学园，《理想国》提出哲人王统治，著作保存了苏格拉底思想。",rel:[{i:"socrates",t:"受业"},{i:"aristotle",t:"授业"},{i:"parmenides",t:"受影响"}]},
{id:"aristotle",n:"亚里士多德",e:"Aristotle",c:"greece",r:"thinker",d:"前384—前322",b:"古代最博学者，建立吕克昂，奠定逻辑学、生物学、政治学、伦理学、诗学，亚历山大的老师。",rel:[{i:"plato",t:"受业"},{i:"alexander",t:"授业"},{i:"theophrastus",t:"授业"},{i:"democritus",t:"批判发展"}]},
{id:"theophrastus",n:"西奥弗拉斯图斯",e:"Theophrastus",c:"greece",r:"thinker",d:"约前371—前287",b:"亚里士多德接班人，植物学奠基者，《论植物》，古代最重要的植物学家。",rel:[{i:"aristotle",t:"受业/继承学园"}]},
{id:"demosthenes",n:"德谟斯提尼",e:"Demosthenes",c:"greece",r:"other",d:"前384—前322",b:"雅典最伟大演说家，用小石子练口吃，《腓力斯反驳》系列反对马其顿，被追杀，以毒药自尽。",rel:[{i:"philip2",t:"激烈反对"},{i:"alexander",t:"政治对手"}]},
{id:"epaminondas",n:"伊帕明农达",e:"Epaminondas",c:"greece",r:"general",d:"前418—前362",b:"底比斯将领，发明斜线阵，留克特拉战役打破斯巴达不败神话，阵亡后底比斯霸权终结。",rel:[{i:"philip2",t:"影响马其顿军事改革"}]},
{id:"philip2",n:"腓力二世",e:"Philip II",c:"greece",r:"ruler",d:"前382—前336",b:"马其顿国王，发明马其顿方阵，喀罗尼亚战役征服全希腊，在女儿婚礼上被刺杀。",rel:[{i:"alexander",t:"父亲"},{i:"demosthenes",t:"政治对手"},{i:"epaminondas",t:"学习斜线阵"}]},
{id:"alexander",n:"亚历山大大帝",e:"Alexander the Great",c:"greece",r:"ruler",d:"前356—前323",b:"13年征服波斯、埃及到印度河，建立古代最大帝国，传播希腊化文化，32岁在巴比伦去世。",rel:[{i:"aristotle",t:"受业"},{i:"philip2",t:"继承"},{i:"darius3",t:"战场对手"},{i:"ptolemy",t:"将领后继承"},{i:"seleucus",t:"将领后继承"},{i:"diogenes",t:"传说交集"}]},
{id:"diogenes",n:"第欧根尼",e:"Diogenes",c:"greece",r:"thinker",d:"约前412—前323",b:"犬儒派，住木桶，白天持灯找'诚实的人'，对亚历山大说'请不要挡住我的阳光'。",rel:[{i:"alexander",t:"传说交集"},{i:"plato",t:"批评"}]},
{id:"epicurus",n:"伊壁鸠鲁",e:"Epicurus",c:"greece",r:"thinker",d:"前341—前270",b:"伊壁鸠鲁派，快乐是最高善但精神快乐胜于肉体，友谊是幸福核心，花园学派接纳女性和奴隶。",rel:[{i:"democritus",t:"思想传承"},{i:"zeno_stoic",t:"同时代对立学派"}]},
{id:"zeno_stoic",n:"斯多葛芝诺",e:"Zeno of Citium",c:"greece",r:"thinker",d:"约前334—前262",b:"斯多葛派创始人，在雅典门廊讲学，理性顺从自然，影响了马可·奥勒留和整个罗马哲学。",rel:[{i:"epicurus",t:"对立学派"},{i:"seneca",t:"思想传承"}]},
{id:"archimedes",n:"阿基米德",e:"Archimedes",c:"greece",r:"thinker",d:"约前287—前212",b:"古代最伟大数学物理学家，浮力原理、杠杆原理，计算π近似值，被罗马兵杀死时仍在做数学。",rel:[{i:"ptolemy",t:"托勒密王朝时期"}]},
{id:"ptolemy",n:"托勒密一世",e:"Ptolemy I",c:"greece",r:"ruler",d:"前367—前283",b:"亚历山大童年伙伴和将领，建立埃及托勒密王朝，建亚历山大里亚图书馆。",rel:[{i:"alexander",t:"伙伴/将领"},{i:"seleucus",t:"竞争对手"}]},
{id:"seleucus",n:"塞琉古一世",e:"Seleucus I",c:"greece",r:"ruler",d:"前358—前281",b:"亚历山大帝国分裂后建立塞琉古帝国，控制中东、波斯，与印度孔雀王朝有外交往来。",rel:[{i:"alexander",t:"将领"},{i:"ptolemy",t:"竞争对手"},{i:"chandragupta",t:"外交岳父"}]},

// ═══ 罗马 ═══
{id:"scipio",n:"西庇阿",e:"Scipio Africanus",c:"rome",r:"general",d:"前236—前183",b:"扎马战役击败汉尼拔，获封阿非利加努斯，罗马最重要将领之一，后被政敌打压郁郁而终。",rel:[{i:"hannibal",t:"战场宿敌"}]},
{id:"hannibal",n:"汉尼拔",e:"Hannibal Barca",c:"rome",r:"general",d:"前247—前183",b:"翻越阿尔卑斯山，坎尼战役歼灭七万罗马军，古代最伟大军事天才之一，被罗马追逼自尽。",rel:[{i:"scipio",t:"宿敌"}]},
{id:"gracchus_t",n:"提比略·格拉古",e:"Tiberius Gracchus",c:"rome",r:"ruler",d:"前163—前133",b:"试图重分公地给平民，被元老院保守派组织暴徒打死，共和国暴力政治的开始。",rel:[{i:"gracchus_g",t:"弟弟"}]},
{id:"gracchus_g",n:"盖尤斯·格拉古",e:"Gaius Gracchus",c:"rome",r:"ruler",d:"前154—前121",b:"继续土地改革，被元老院镇压，命令奴隶杀死自己，共和国危机激化节点。",rel:[{i:"gracchus_t",t:"哥哥"},{i:"marius",t:"改革后继"}]},
{id:"spartacus",n:"斯巴达克斯",e:"Spartacus",c:"rome",r:"general",d:"约前111—前71",b:"色雷斯角斗士，领导罗马最大规模奴隶起义，横扫意大利，6000起义者被钉死大道两旁。",rel:[{i:"crassus",t:"被镇压"}]},
{id:"marius",n:"马略",e:"Gaius Marius",c:"rome",r:"general",d:"前157—前86",b:"七次执政官，军事改革创造职业军人制，使军队忠于将领而非国家，是内战根源。",rel:[{i:"sulla",t:"政敌内战"},{i:"caesar",t:"舅父"},{i:"gracchus_g",t:"后继"}]},
{id:"sulla",n:"苏拉",e:"Sulla",c:"rome",r:"general",d:"前138—前78",b:"第一个率军进入罗马城的将领，建立独裁统治后主动辞职恢复共和，奠定恺撒效仿先例。",rel:[{i:"marius",t:"政敌"},{i:"caesar",t:"政治打压过"}]},
{id:"crassus",n:"克拉苏",e:"Crassus",c:"rome",r:"ruler",d:"约前115—前53",b:"罗马最富的人，前三头之一，卡莱战役被帕提亚骑兵歼灭，熔金灌口，罗马东扩重大挫败。",rel:[{i:"caesar",t:"前三头"},{i:"pompey",t:"前三头"},{i:"spartacus",t:"镇压起义"}]},
{id:"pompey",n:"庞培",e:"Pompey",c:"rome",r:"general",d:"前106—前48",b:"罗马最著名将领，清除地中海海盗，征服东方，前三头之一，法萨卢斯被击败后逃往埃及被刺。",rel:[{i:"caesar",t:"内战对手"},{i:"crassus",t:"前三头"},{i:"cicero",t:"政治盟友"}]},
{id:"cicero",n:"西塞罗",e:"Cicero",c:"rome",r:"thinker",d:"前106—前43",b:"罗马最伟大演说家，揭发卡提林阴谋，《论共和国》，安东尼命令下被杀，手被钉于讲台。",rel:[{i:"pompey",t:"政治盟友"},{i:"caesar",t:"共存"},{i:"mark_antony",t:"被杀"}]},
{id:"caesar",n:"尤利乌斯·恺撒",e:"Julius Caesar",c:"rome",r:"ruler",d:"前100—前44",b:"高卢战争，卢比孔河，《高卢战记》，改革历法，三月诺奈被布鲁图斯等23人刺杀。",rel:[{i:"pompey",t:"内战对手"},{i:"crassus",t:"前三头"},{i:"cleopatra",t:"政治情人"},{i:"brutus",t:"被刺"},{i:"octavian",t:"养子/继承人"},{i:"marius",t:"舅父"}]},
{id:"cleopatra",n:"克利奥帕特拉七世",e:"Cleopatra VII",c:"rome",r:"ruler",d:"前69—前30",b:"埃及最后一位法老，与恺撒和安东尼分别联盟，古代最著名政治女性，以毒蛇自杀。",rel:[{i:"caesar",t:"政治情人"},{i:"mark_antony",t:"爱侣联盟"},{i:"octavian",t:"失败于"}]},
{id:"brutus",n:"布鲁图斯",e:"Brutus",c:"rome",r:"other",d:"前85—前42",b:"刺杀恺撒主谋之一，'你也有份，布鲁图？'，腓力战役被屋大维击败后自杀。",rel:[{i:"caesar",t:"刺杀"},{i:"octavian",t:"被击败"}]},
{id:"mark_antony",n:"马克·安东尼",e:"Mark Antony",c:"rome",r:"general",d:"前83—前30",b:"恺撒最重要将领，葬礼演说激起民愤，与克利奥帕特拉爱情是古代最著名故事，亚克兴战败自杀。",rel:[{i:"caesar",t:"副将"},{i:"cleopatra",t:"爱侣"},{i:"octavian",t:"最终对手"},{i:"cicero",t:"下令杀"}]},
{id:"octavian",n:"奥古斯都",e:"Augustus",c:"rome",r:"ruler",d:"前63—公元14",b:"罗马帝国第一位皇帝，设计元首制维持200年罗马和平，自称第一公民。",rel:[{i:"caesar",t:"养子/继承人"},{i:"mark_antony",t:"击败"},{i:"tiberius",t:"继承人"},{i:"agrippa",t:"最重要将领"}]},
{id:"agrippa",n:"阿格里帕",e:"Marcus Agrippa",c:"rome",r:"general",d:"前64—前12",b:"奥古斯都最重要将领，亚克兴海战真正指挥者，修建万神殿，是帝国建设核心执行者。",rel:[{i:"octavian",t:"最重要战友"}]},
{id:"tiberius",n:"提比略",e:"Tiberius",c:"rome",r:"ruler",d:"前42—公元37",b:"奥古斯都继子，能干多疑，晚年退居卡普里岛。耶稣在其统治期间被钉十字架。",rel:[{i:"octavian",t:"继承"},{i:"jesus",t:"在位期间钉十字架"}]},
{id:"nero",n:"尼禄",e:"Nero",c:"rome",r:"ruler",d:"公元37—68",b:"暴君，64年罗马大火嫁祸基督徒，开创系统迫害，最终被宣布为公敌，自杀前喊'我死一个多大的艺术家！'",rel:[{i:"tiberius",t:"最终继承"},{i:"seneca",t:"老师被赐死"},{i:"peter_apos",t:"在位时殉道"},{i:"paul_apos",t:"在位时殉道"}]},
{id:"seneca",n:"塞内卡",e:"Seneca",c:"rome",r:"thinker",d:"约前4—公元65",b:"斯多葛派哲学家，尼禄导师，《书信集》是晚期罗马文学巅峰，最终被尼禄赐死，从容切断动脉。",rel:[{i:"nero",t:"辅政被赐死"},{i:"marcus_aurelius",t:"思想传承"},{i:"zeno_stoic",t:"传承斯多葛"}]},
{id:"trajan",n:"图拉真",e:"Trajan",c:"rome",r:"ruler",d:"公元53—117",b:"五贤帝，征服达契亚，帝国最大疆域缔造者，图拉真柱记录战争，被称最好的皇帝。",rel:[{i:"hadrian",t:"继承人"}]},
{id:"hadrian",n:"哈德良",e:"Hadrian",c:"rome",r:"ruler",d:"公元76—138",b:"旅行家皇帝，建哈德良长城，热爱希腊文化，爱人安提诺乌斯溺死后将其神格化。",rel:[{i:"trajan",t:"继承"},{i:"antoninus",t:"继承人"},{i:"antinous",t:"爱人"}]},
{id:"antinous",n:"安提诺乌斯",e:"Antinous",c:"rome",r:"other",d:"约111—130",b:"哈德良的爱人，比提尼亚少年，130年神秘溺死于尼罗河，哈德良在帝国各地建立其雕像神庙。",rel:[{i:"hadrian",t:"被哈德良挚爱"}]},
{id:"antoninus",n:"安东尼·庇护",e:"Antoninus Pius",c:"rome",r:"ruler",d:"公元86—161",b:"五贤帝，在位23年无战争，政务宽和，罗马和平最平静的顶峰，被视为理想统治者典范。",rel:[{i:"hadrian",t:"继承"},{i:"marcus_aurelius",t:"养父"}]},
{id:"marcus_aurelius",n:"马可·奥勒留",e:"Marcus Aurelius",c:"rome",r:"ruler",d:"公元121—180",b:"哲学家皇帝，斯多葛派，《沉思录》是西方最重要的心灵修炼著作，应对北方战争和安东尼瘟疫。",rel:[{i:"antoninus",t:"继承"},{i:"seneca",t:"思想传承"},{i:"commodus",t:"儿子"}]},
{id:"commodus",n:"康茂德",e:"Commodus",c:"rome",r:"ruler",d:"公元161—192",b:"以角斗士自居（宣称自己是赫拉克勒斯），把罗马改名为科莫德斯城，被情人和大臣合谋杀死。",rel:[{i:"marcus_aurelius",t:"儿子/衰落标志"}]},
{id:"diocletian",n:"戴克里先",e:"Diocletian",c:"rome",r:"ruler",d:"公元245—311",b:"结束三世纪危机，四帝共治，301年最高价格敕令，303年大迫害基督徒，主动退位种卷心菜。",rel:[{i:"constantine",t:"政治先驱"}]},
{id:"constantine",n:"君士坦丁一世",e:"Constantine I",c:"rome",r:"ruler",d:"公元272—337",b:"313年米兰敕令宗教自由，325年尼西亚大公会议三位一体，330年迁都君士坦丁堡，第一位基督教皇帝。",rel:[{i:"diocletian",t:"继承体制"},{i:"jesus",t:"推广其宗教"},{i:"augustine",t:"奠定基础"}]},
{id:"augustine",n:"奥古斯丁",e:"Augustine of Hippo",c:"rome",r:"thinker",d:"公元354—430",b:"西方基督教神学最重要思想家，《忏悔录》《上帝之城》，系统化原罪论，奠定中世纪神学。",rel:[{i:"constantine",t:"继承时代"},{i:"jesus",t:"神学阐释"}]},

// ═══ 波斯 ═══
{id:"cyrus",n:"居鲁士大帝",e:"Cyrus the Great",c:"persia",r:"ruler",d:"约前600—前530",b:"波斯帝国缔造者，征服米底吕底亚巴比伦，居鲁士圆柱释放被囚民族，犹太人称其为弥赛亚。",rel:[{i:"cambyses",t:"儿子"},{i:"darius1",t:"后继"},{i:"croesus",t:"征服"},{i:"zoroaster",t:"信仰"}]},
{id:"croesus",n:"克罗伊苏斯",e:"Croesus",c:"persia",r:"ruler",d:"约前595—前547",b:"吕底亚末代王，极度富有，向德尔菲神谕问吉凶后被居鲁士征服，神谕的双关语讽刺典故。",rel:[{i:"cyrus",t:"被征服"}]},
{id:"cambyses",n:"冈比西斯二世",e:"Cambyses II",c:"persia",r:"ruler",d:"前530—前522在位",b:"居鲁士之子，征服埃及，据报杀死阿庇斯神牛亵渎宗教，神秘死亡，或自杀或被刺。",rel:[{i:"cyrus",t:"继承"},{i:"darius1",t:"被继承"}]},
{id:"darius1",n:"大流士一世",e:"Darius I",c:"persia",r:"ruler",d:"前522—前486在位",b:"波斯帝国真正组织者，行省制、王道、波斯波利斯，马拉松战役败于希腊，历史上最伟大行政者之一。",rel:[{i:"cambyses",t:"继承"},{i:"xerxes",t:"传位"},{i:"miltiades",t:"战场对手"}]},
{id:"xerxes",n:"薛西斯一世",e:"Xerxes I",c:"persia",r:"ruler",d:"前486—前465在位",b:"建两条海峡浮桥，率史上最大古代军队侵希腊，萨拉米斯惨败，晚年在宫廷阴谋中被杀。",rel:[{i:"darius1",t:"继承"},{i:"leonidas",t:"战场对手"},{i:"themistocles",t:"被智谋击败"}]},
{id:"artaxerxes",n:"阿塔薛西斯一世",e:"Artaxerxes I",c:"persia",r:"ruler",d:"前465—前424在位",b:"薛西斯之子，与希腊签订卡利亚斯和约结束希波战争，统治期间犹太人重建耶路撒冷城墙。",rel:[{i:"xerxes",t:"继承"}]},
{id:"darius3",n:"大流士三世",e:"Darius III",c:"persia",r:"ruler",d:"前380—前330",b:"波斯帝国末代皇帝，三次面对亚历山大均落败，最终被自己的总督贝苏斯刺杀。",rel:[{i:"alexander",t:"战场对手被击败"}]},
{id:"zoroaster",n:"琐罗亚斯德",e:"Zoroaster",c:"persia",r:"religious",d:"约前1500—前1000（有争议）",b:"拜火教创始人，阿胡拉·马兹达，善恶二元论，末世审判天堂地狱，深刻影响犹太教和基督教。",rel:[{i:"cyrus",t:"信仰影响"},{i:"jesus",t:"间接神学影响"}]},

// ═══ 印度/佛教 ═══
{id:"buddha",n:"悉达多（佛陀）",e:"Siddhartha Gautama",c:"india",r:"religious",d:"约前563—前483",b:"佛教创始人，四门出游，菩提树下开悟，四圣谛八正道，弘法45年，涅槃于拘尸那揭罗。",rel:[{i:"ananda",t:"侍者弟子"},{i:"mahakassapa",t:"首席弟子"},{i:"bimbisara",t:"护法国王"},{i:"ajatasattu",t:"后皈依"},{i:"ashoka",t:"信仰传播"}]},
{id:"mahavira",n:"大雄（筏驮摩那）",e:"Mahavira",c:"india",r:"religious",d:"约前599—前527",b:"耆那教集大成者，与佛陀同时代，极端不杀生主义，裸体苦行，42岁开悟，印度最古老活宗教。",rel:[{i:"buddha",t:"同时代"}]},
{id:"ananda",n:"阿难",e:"Ananda",c:"india",r:"religious",d:"约前500年代",b:"佛陀最亲近侍者25年，记忆力超群，第一次结集背诵大量经文，为女性出家权向佛请求。",rel:[{i:"buddha",t:"侍者"},{i:"mahakassapa",t:"同门结集"}]},
{id:"mahakassapa",n:"摩诃迦叶",e:"Mahakassapa",c:"india",r:"religious",d:"约前500年代",b:"佛陀首席弟子，主持第一次结集500阿罗汉，禅宗视其为禅的第一传人（拈花微笑）。",rel:[{i:"buddha",t:"首席弟子"},{i:"ananda",t:"同门"}]},
{id:"bimbisara",n:"频婆娑罗王",e:"Bimbisara",c:"india",r:"ruler",d:"约前544—前492",b:"摩揭陀国王，最重要佛教护法者，捐献竹林精舍，后被儿子阿阇世王幽禁而死。",rel:[{i:"buddha",t:"护法皈依"},{i:"ajatasattu",t:"被儿子弑杀"}]},
{id:"ajatasattu",n:"阿阇世王",e:"Ajatasattu",c:"india",r:"ruler",d:"约前492—前460在位",b:"弑父夺位，后悔皈依佛教，主持佛教第一次结集，早期佛教政治史的关键人物。",rel:[{i:"bimbisara",t:"弑父"},{i:"buddha",t:"皈依"},{i:"mahakassapa",t:"支持结集"}]},
{id:"chanakya",n:"考底利耶",e:"Chanakya/Kautilya",c:"india",r:"thinker",d:"约前350—前275",b:"古印度最重要政治思想家，《政事论》是印度版《君主论》，辅佐旃陀罗笈多建立孔雀帝国。",rel:[{i:"chandragupta",t:"辅佐"}]},
{id:"chandragupta",n:"旃陀罗笈多",e:"Chandragupta Maurya",c:"india",r:"ruler",d:"约前340—前298",b:"孔雀帝国创始人，统一印度次大陆大部，与塞琉古有外交往来，晚年出家成耆那教苦行者。",rel:[{i:"chanakya",t:"被辅佐"},{i:"ashoka",t:"祖父"},{i:"seleucus",t:"外交/岳父"}]},
{id:"ashoka",n:"阿育王",e:"Ashoka",c:"india",r:"ruler",d:"约前304—前232",b:"孔雀帝国最伟大皇帝，羯陵伽战争后皈依佛教，颁布石柱法敕，派传教团使佛教成世界性宗教。",rel:[{i:"buddha",t:"信仰传播"},{i:"chandragupta",t:"孙子"}]},
{id:"nagarjuna",n:"龙树",e:"Nagarjuna",c:"india",r:"religious",d:"约公元150—250",b:"大乘佛教最重要哲学家，中观哲学，'诸法皆空'，《中论》奠定大乘佛教理论基础，第二佛陀。",rel:[{i:"buddha",t:"思想传承"}]},

// ═══ 基督教 · 兴于罗马帝国 (并入罗马) ═══
{id:"jesus",n:"耶稣基督",e:"Jesus Christ",c:"rome",r:"religious",d:"约前4—公元30",b:"基督教创始人，登山宝训，被钉十字架，三日复活，影响西方文明两千年。",rel:[{i:"paul_apos",t:"思想传播"},{i:"peter_apos",t:"首席门徒"},{i:"tiberius",t:"在位期间殉道"},{i:"constantine",t:"信仰国教化"}]},
{id:"peter_apos",n:"彼得",e:"Peter",c:"rome",r:"religious",d:"约前1—公元68",b:"十二门徒之首，早期教会领袖，据传在罗马被倒钉十字架殉道，梵蒂冈圣彼得大教堂建于其墓上。",rel:[{i:"jesus",t:"首席门徒"},{i:"paul_apos",t:"同僚"},{i:"nero",t:"在位时殉道"}]},
{id:"paul_apos",n:"保罗",e:"Paul of Tarsus",c:"rome",r:"religious",d:"约公元5—67",b:"基督教向世界传播的最重要人物，大马士革顿悟皈依，三次传教旅程，因信称义神学。",rel:[{i:"jesus",t:"使徒/传道"},{i:"peter_apos",t:"同僚"},{i:"nero",t:"在位时殉道"}]},
// ═══ 补全章节：铁器·字母·先知 (前1000–前600) ═══
// 中国·西周
{id:"zhouwu",n:"周武王",e:"King Wu of Zhou",c:"china",r:"ruler",d:"约前1046在位",b:"周朝开国君主。前1046年牧野之战灭商纣，建立周朝、定都镐京、大封诸侯，结束商朝六百年统治。",rel:[{i:"zhougong",t:"弟"},{i:"jiangziya",t:"重用军师"}]},
{id:"zhougong",n:"周公",e:"Duke of Zhou",c:"china",r:"thinker",d:"约前11世纪",b:"武王之弟姬旦。武王死后辅佐成王，东征平定三监之乱，制礼作乐、推行分封宗法、营建洛邑，奠定中华礼乐文明，功成还政。孔子终身景仰的圣人。",rel:[{i:"zhouwu",t:"兄"},{i:"kongzi",t:"被其景仰"}]},
{id:"jiangziya",n:"姜子牙",e:"Jiang Ziya",c:"china",r:"general",d:"约前11世纪",b:"吕尚，周文王武王的军师，助周灭商首功之臣。传说垂钓渭水待明主'愿者上钩'，后世尊为兵家与谋略之祖。",rel:[{i:"zhouwu",t:"辅佐"}]},
// 西亚·两河
{id:"ashurbanipal",n:"亚述巴尼拔",e:"Ashurbanipal",c:"near_east",r:"ruler",d:"前668—前627在位",b:"新亚述末代雄主，军事强盛，更以在尼尼微建立古代最大图书馆著称，系统收藏楔形文字泥板，为后世保存《吉尔伽美什史诗》等两河无价文献。",rel:[{i:"nebuchadnezzar2",t:"亚述衰亡后巴比伦继兴"}]},
{id:"nebuchadnezzar2",n:"尼布甲尼撒二世",e:"Nebuchadnezzar II",c:"near_east",r:"ruler",d:"前605—前562在位",b:"新巴比伦最伟大君主，重建巴比伦城与伊什塔尔门，传说建空中花园。前586年灭犹大、毁第一圣殿，掳走犹太人，制造'巴比伦之囚'。",rel:[{i:"david",t:"灭其后裔之国"}]},
// 黎凡特·以色列
{id:"david",n:"大卫王",e:"King David",c:"levant",r:"ruler",d:"约前1010—前970在位",b:"以色列联合王国第二位君主。少年以投石击杀巨人歌利亚，统一十二支派、定都耶路撒冷，传为《诗篇》多篇作者，犹太/基督/伊斯兰三教共尊的伟大君王。",rel:[{i:"solomon",t:"子"}]},
{id:"solomon",n:"所罗门王",e:"King Solomon",c:"levant",r:"ruler",d:"约前970—前931在位",b:"大卫之子，以智慧著称('所罗门的审判')。在位时国力鼎盛，建造耶路撒冷第一圣殿。死后王国分裂为北国以色列与南国犹大。",rel:[{i:"david",t:"父"}]},
{id:"isaiah",n:"以赛亚",e:"Isaiah",c:"levant",r:"religious",d:"约前8世纪",b:"以色列最重要的先知之一，宣讲唯一神的公义与对弥赛亚(救世主)的盼望，《以赛亚书》深刻影响犹太教与基督教。",rel:[{i:"david",t:"预言大卫子孙弥赛亚"},{i:"solomon",t:"希伯来先知传统"}]},
// 希腊·古风
{id:"homer",n:"荷马",e:"Homer",c:"greece",r:"thinker",d:"约前8世纪",b:"古希腊盲诗人，相传作《伊利亚特》《奥德赛》两大史诗，奠定希腊神话、荣誉观与文学传统，西方文学的源头。",rel:[{i:"solon",t:"荷马史诗哺育的雅典"},{i:"pythagoras",t:"希腊文化共同源头"}]},
// 罗马·王政
{id:"romulus",n:"罗慕路斯",e:"Romulus",c:"rome",r:"ruler",d:"传说前753",b:"罗马建城传说中的创建者与首位国王。与孪生弟雷穆斯被母狼哺育，前753年建罗马城，后世尊为国父。",rel:[{i:"scipio",t:"罗慕路斯之城的捍卫者"},{i:"cicero",t:"罗马传统的传承者"}]},
// ═══ 补全批次02：笈多 · 道教 · 犹太战争 ═══
// 印度·笈多
{id:"samudragupta",n:"沙摩陀罗·笈多",e:"Samudragupta",c:"india",r:"ruler",d:"约335—375在位",b:"笈多王朝第三位君主，军事天才，南征北战几乎统一北印度，被誉为'印度的拿破仑'。其功业刻于阿拉哈巴德石柱(借用阿育王旧柱)。",rel:[{i:"chandragupta2",t:"父子"}]},
{id:"chandragupta2",n:"超日王",e:"Chandragupta II",c:"india",r:"ruler",d:"约380—415在位",b:"旃陀罗·笈多二世，称'超日王'(Vikramaditya)。笈多黄金时代的顶峰君主，国力鼎盛、文化繁荣，中国高僧法显此时游历印度并盛赞其太平。",rel:[{i:"samudragupta",t:"父子"},{i:"kalidasa",t:"宫廷诗人"}]},
{id:"aryabhata",n:"阿耶波多",e:"Aryabhata",c:"india",r:"thinker",d:"476—550",b:"笈多时代伟大数学家与天文学家。《阿耶波多历书》(499)提出地球绕轴自转、计算圆周率至四位小数、科学解释日月食，运用十进制与'零'，领先世界千年。",rel:[{i:"chanakya",t:"印度学术传统"},{i:"nagarjuna",t:"印度智识传统"}]},
{id:"kalidasa",n:"迦梨陀娑",e:"Kalidasa",c:"india",r:"thinker",d:"约4—5世纪",b:"古典梵语最伟大的诗人与剧作家，代表作《沙恭达罗》《云使》，被誉为'印度的莎士比亚'，笈多文学黄金时代的象征。",rel:[{i:"chandragupta2",t:"侍奉"}]},
// 中国·道教
{id:"zhang_daoling",n:"张道陵",e:"Zhang Daoling",c:"china",r:"religious",d:"34—156",b:"道教创始人之一。142年在四川创'五斗米道'(天师道)，尊老子为太上老君、奉《道德经》为经典，以符水治病、建立教团组织，使先秦道家哲学演变为有组织的宗教。",rel:[{i:"laozi",t:"尊奉为教主"}]},
// 罗马/犹太·犹太战争
{id:"titus",n:"提图斯",e:"Titus",c:"rome",r:"ruler",d:"39—81",b:"罗马弗拉维王朝皇帝。公元70年率军攻陷耶路撒冷、焚毁第二圣殿，罗马提图斯凯旋门浮雕刻有从圣殿掠走的七枝金灯台。后继父位为帝，在位时维苏威火山爆发(庞贝)。",rel:[{i:"josephus",t:"随军史家"}]},
{id:"josephus",n:"约瑟夫斯",e:"Flavius Josephus",c:"levant",r:"thinker",d:"约37—100",b:"犹太祭司与历史学家。犹太战争中先抗罗马后投降，成为提图斯的随军记录者，著《犹太战争史》《犹太古史》，是研究第二圣殿时代与早期基督教背景的关键史料。",rel:[{i:"titus",t:"随其记录战争"}]},
];
if(typeof window!=='undefined')window.CLASSICAL_PEOPLE=CLASSICAL_PEOPLE;

// ── 人物代表图标 (相当于头像，反映其身份/文明/文化) ──
const CLASSICAL_ICON = {
  // 补全章节 · 铁器字母先知
  zhouwu:'👑',zhougong:'📜',jiangziya:'🎣',ashurbanipal:'📚',nebuchadnezzar2:'👑',
  david:'🎵',solomon:'⚖️',isaiah:'🕊️',homer:'🎭',romulus:'🐺',
  // 补全批次02 · 笈多/道教/犹太战争
  samudragupta:'⚔️',chandragupta2:'👑',aryabhata:'🔢',kalidasa:'📜',
  zhang_daoling:'☯️',titus:'⚔️',josephus:'📖',
  // 中国 · 春秋战国
  kongzi:'📜',laozi:'☯️',guanzhong:'⚖️',baoshuya:'🤝',qihuan:'👑',jinhuan:'👑',zichan:'⚖️',yanzi:'🗣️',
  mencius:'📜',zhuangzi:'📜',mozi:'🛡️',yangzhu:'📜',huizi:'💬',gongsunlong:'📜',sunzi:'⚔️',helv:'👑',
  wuzixu:'🗡️',goujian:'🗡️',fucha:'👑',xishi:'👤',fanli:'💰',xunzi:'📜',hanfeizi:'⚖️',shangyang:'⚖️',
  qin_xiaogong:'👑',shenbuhai:'⚖️',suqin:'🗣️',zhangyi:'🗣️',guiguzi:'🧙',sunbin:'⚔️',pangjuan:'⚔️',
  // 中国 · 秦汉
  qin_shihuang:'👑',lisi:'📜',zhaoago:'📜',xiangyu:'⚔️',fanzheng:'📜',liubang:'👑',xiao_he:'📊',
  hanxin:'⚔️',zhanglianghan:'🧠',lvhou:'👸',dongzhongshu:'📜',wudi_han:'👑',weiqing:'⚔️',huoqubing:'🐎',
  zhangqian:'🐫',simarqian:'📖',liuche:'🖌️',
  // 波斯
  cyrus:'👑',croesus:'💰',cambyses:'👑',darius1:'👑',xerxes:'👑',artaxerxes:'👑',darius3:'👑',zoroaster:'🔥',
  // 印度/佛教
  buddha:'☸️',mahavira:'🧘',ananda:'🙏',mahakassapa:'🧘',bimbisara:'👑',ajatasattu:'👑',
  chanakya:'📖',chandragupta:'👑',ashoka:'🦁',nagarjuna:'☸️',
  // 希腊
  thales:'💧',anaximander:'🗺️',pythagoras:'📐',heraclitus:'🔥',parmenides:'🌀',democritus:'⚛️',protagoras:'🗣️',
  solon:'⚖️',peisistratos:'👑',cleisthenes:'🗳️',miltiades:'⚔️',leonidas:'🛡️',themistocles:'⛵',pericles:'🏛️',
  aspasia:'👤',aeschylus:'🎭',sophocles:'🎭',euripides:'🎭',aristophanes:'🎭',herodotus:'📜',thucydides:'📜',
  socrates:'🏛️',xenophon:'📜',alcibiades:'⚔️',plato:'💡',aristotle:'📚',theophrastus:'🌿',demosthenes:'🗣️',
  epaminondas:'⚔️',philip2:'🛡️',alexander:'🌍',diogenes:'🏛️',epicurus:'🏛️',zeno_stoic:'🏛️',archimedes:'📐',
  ptolemy:'📚',seleucus:'🐘',
  // 罗马
  scipio:'⚔️',hannibal:'🐘',gracchus_t:'✊',gracchus_g:'✊',spartacus:'⛓️',marius:'🛡️',sulla:'⚔️',crassus:'💰',
  pompey:'⚔️',cicero:'🗣️',caesar:'👑',cleopatra:'🐍',brutus:'🗡️',mark_antony:'⚔️',octavian:'👑',agrippa:'⚓',
  tiberius:'👑',nero:'🔥',seneca:'📜',trajan:'🏛️',hadrian:'🧱',antinous:'👤',antoninus:'👑',marcus_aurelius:'📖',
  commodus:'🗡️',diocletian:'👑',constantine:'✝️',augustine:'📖',
  // 跨文明/基督教
  jesus:'✝️',peter_apos:'🔑',paul_apos:'📜',silk:'🐫',
};
const ROLE_ICON_FALLBACK = {ruler:'👑',general:'⚔️',thinker:'📜',religious:'🕊️',other:'🔹'};
function personIconOf(p){ if(!p) return '👤'; const id=typeof p==='string'?p:p.id; if(CLASSICAL_ICON[id])return CLASSICAL_ICON[id]; const role=typeof p==='object'?p.r:null; return ROLE_ICON_FALLBACK[role]||'👤'; }
if(typeof window!=='undefined'){window.CLASSICAL_ICON=CLASSICAL_ICON;window.personIconOf=personIconOf;}
