// ════════════════════════════════════════════════════════════════
// 🌐 早期文明 · 全局浏览器数据层 (Explorer Data)
// 扩充 4 个维度：人物朋友圈 / 事件因果链 / 对比卡矩阵 / 同时在线
// 时间范围：前 3500 - 前 1000 BCE
// ════════════════════════════════════════════════════════════════

const EARLY_CIV_EXPLORER = {

  // ─────────────────────────────────────────────
  // 1. 10 个文明 · 时间带 (生命周期 + 颜色 + 简介)
  // ─────────────────────────────────────────────
  civilizations: [
    { id:'sumer',     name:'苏美尔',          start:-3500, end:-2004, region:'美索不达米亚',  color:'#c86820', icon:'📜', lane:1 },
    { id:'egypt_old', name:'古埃及·古王国',    start:-3100, end:-2181, region:'尼罗河',        color:'#e8a040', icon:'🔺', lane:2 },
    { id:'indus',     name:'印度河文明',       start:-2600, end:-1900, region:'印度河流域',     color:'#a08850', icon:'🧱', lane:3 },
    { id:'akkad',     name:'阿卡德帝国',       start:-2334, end:-2154, region:'美索不达米亚',  color:'#b04830', icon:'👑', lane:1 },
    { id:'egypt_mid', name:'古埃及·中王国',    start:-2055, end:-1650, region:'尼罗河',        color:'#e8b050', icon:'🌅', lane:2 },
    { id:'minoan',    name:'米诺斯',           start:-2000, end:-1450, region:'爱琴海',         color:'#2080a0', icon:'🐂', lane:5 },
    { id:'babylon',   name:'古巴比伦',         start:-1894, end:-1595, region:'美索不达米亚',  color:'#8a4090', icon:'⚖', lane:1 },
    { id:'shang',     name:'商朝',             start:-1600, end:-1046, region:'黄河',          color:'#a02030', icon:'⚱️', lane:4 },
    { id:'hittite',   name:'赫梯帝国',         start:-1600, end:-1180, region:'安纳托利亚',     color:'#506890', icon:'🛡', lane:6 },
    { id:'mycenae',   name:'迈锡尼',           start:-1600, end:-1100, region:'爱琴海',         color:'#1880b0', icon:'🦁', lane:5 },
    { id:'egypt_new', name:'古埃及·新王国',    start:-1550, end:-1070, region:'尼罗河',        color:'#d4a020', icon:'👁', lane:2 },
    { id:'collapse',  name:'青铜大崩溃',       start:-1200, end:-1150, region:'地中海东部',     color:'#7a2818', icon:'💥', lane:7, isEvent:true },
  ],

  // ─────────────────────────────────────────────
  // 2. 重大历史人物 · 朋友圈 (50+ 人)
  //    每个人含: 生卒年 / 文明 / 角色 / 朋友圈 / 发明/贡献
  //    relationships 类型: friend, mentor, enemy, family, contemporary, successor
  // ─────────────────────────────────────────────
  people: [
    // ── 苏美尔 ──
    { id:'gilgamesh', name:'Gilgamesh 吉尔伽美什', civ:'sumer', born:-2700, died:-2650, role:'Uruk 第五王',
      portrait:'👑', desc:'传奇国王，《吉尔伽美什史诗》主角。寻求永生失败但留下文学不朽。',
      inventions:['Uruk 城墙(传说)','开启文学传统'],
      relationships:[{to:'enkidu',type:'friend',note:'最好朋友，死后吉尔伽美什开始思考死亡'}] },
    { id:'enkidu', name:'Enkidu 恩奇都', civ:'sumer', born:-2700, died:-2660, role:'吉尔伽美什挚友',
      portrait:'🐂', desc:'神创造的野人，与吉尔伽美什从敌人变挚友。死亡引发对永生的追问。',
      inventions:[], relationships:[{to:'gilgamesh',type:'friend'}] },
    { id:'enheduanna', name:'Enheduanna 恩赫杜安娜', civ:'akkad', born:-2285, died:-2250, role:'月神大祭司·诗人',
      portrait:'🌙', desc:'Sargon 之女。世界第一位有名字的作家，写过 42 首神庙赞美诗。',
      inventions:['第一首署名诗歌','宗教-政权融合模式'],
      relationships:[{to:'sargon',type:'family',note:'女儿'}] },
    { id:'urnammu', name:'Ur-Nammu 乌尔纳姆', civ:'sumer', born:-2150, died:-2095, role:'Ur III 国王',
      portrait:'⚖', desc:'颁布世界已知最早法典 (比汉谟拉比早 350 年)。建造 Ur 大金字塔。',
      inventions:['Ur-Nammu 法典','Ur 大金字塔','灌溉系统'],
      relationships:[{to:'hammurabi',type:'mentor',note:'法律传统先驱'}] },
    { id:'puabi', name:'Puabi 普阿比女王', civ:'sumer', born:-2600, died:-2550, role:'Ur 王后',
      portrait:'💎', desc:'乌尔王陵主人，陪葬 52 人 + 大量黄金青金石。展示早期王权与殉葬制。',
      inventions:[], relationships:[] },

    // ── 阿卡德 ──
    { id:'sargon', name:'Sargon 萨尔贡大帝', civ:'akkad', born:-2334, died:-2284, role:'第一个皇帝',
      portrait:'⚔️', desc:'世界第一个跨民族多语言帝国创建者。出身传奇 (沥青篮顺河漂下)。',
      inventions:['帝国概念','跨民族中央集权','闪族官僚体系'],
      relationships:[
        {to:'enheduanna',type:'family',note:'女儿，宗教大祭司'},
        {to:'naramsin',type:'family',note:'孙子'},
      ] },
    { id:'naramsin', name:'Naram-Sin 纳拉姆-辛', civ:'akkad', born:-2254, died:-2218, role:'阿卡德第四王',
      portrait:'👹', desc:'第一个自称"神"的人间君主。胜利碑刻其踩在敌人尸体上戴神帽。',
      inventions:['神王 (divine kingship)','名字前加 Dingir 神符'],
      relationships:[{to:'sargon',type:'family',note:'祖父'}] },

    // ── 古埃及 ──
    { id:'narmer', name:'Narmer 那尔迈', civ:'egypt_old', born:-3150, died:-3100, role:'第一位法老',
      portrait:'👑', desc:'统一上下埃及，建立第一王朝。那尔迈调色板是最早法老形象证据。',
      inventions:['统一埃及','法老制度','双重王冠'], relationships:[] },
    { id:'djoser', name:'Djoser 左塞尔', civ:'egypt_old', born:-2700, died:-2670, role:'第三王朝法老',
      portrait:'🔺', desc:'委托 Imhotep 建造世界第一座大型石造金字塔 (阶梯金字塔)。',
      inventions:['金字塔时代开启'],
      relationships:[{to:'imhotep',type:'friend',note:'委托建造金字塔'}] },
    { id:'imhotep', name:'Imhotep 伊姆霍特普', civ:'egypt_old', born:-2700, died:-2620, role:'建筑师·宰相·医生',
      portrait:'🏛', desc:'设计阶梯金字塔，被誉为"医学之父"。2000 年后被神化为治疗之神。',
      inventions:['阶梯金字塔','石造建筑','早期医学'],
      relationships:[{to:'djoser',type:'friend',note:'为他设计金字塔'}] },
    { id:'khufu', name:'Khufu 胡夫 (Cheops)', civ:'egypt_old', born:-2589, died:-2566, role:'第四王朝法老',
      portrait:'🗿', desc:'建造大金字塔。集权达顶峰。',
      inventions:['吉萨大金字塔'], relationships:[] },
    { id:'khafre', name:'Khafre 哈夫拉', civ:'egypt_old', born:-2558, died:-2532, role:'第四王朝法老',
      portrait:'🦁', desc:'建造第二大金字塔 + 狮身人面像 (面相可能是他)。',
      inventions:['狮身人面像 Sphinx'], relationships:[{to:'khufu',type:'family',note:'儿子'}] },

    // ── 古埃及·中王国 (新增) ──
    { id:'mentuhotep', name:'Mentuhotep II 门图霍特普二世', civ:'egypt_mid', born:-2050, died:-2000, role:'中王国创建者',
      portrait:'⚔️', desc:'重新统一埃及，开启中王国黄金时代。',
      inventions:['中王国','底比斯首都'], relationships:[] },

    // ── 印度河 ──
    { id:'harappa_unknown', name:'印度河文明 (匿名)', civ:'indus', born:-2600, died:-1900, role:'未知统治者',
      portrait:'❓', desc:'印度河文明没有发现王陵或统治者形象。可能是分布式权力结构。',
      inventions:['标准化下水道','统一砖块尺寸','未破译文字'], relationships:[] },

    // ── 米诺斯 ──
    { id:'minos_legend', name:'Minos 米诺斯王 (传说)', civ:'minoan', born:-1700, died:-1650, role:'传说君主',
      portrait:'🐂', desc:'希腊神话中迷宫与米诺陶之父。可能是真实国王名字被后人神化。',
      inventions:['Knossos 宫殿 (1300 房间)','海上贸易帝国'], relationships:[] },

    // ── 古巴比伦 ──
    { id:'hammurabi', name:'Hammurabi 汉谟拉比', civ:'babylon', born:-1810, died:-1750, role:'巴比伦第六王',
      portrait:'⚖', desc:'颁布最完整早期法典 (282 条)。用外交+军事统一两河流域。',
      inventions:['汉谟拉比法典','"以眼还眼"','成文法+公开发布'],
      relationships:[
        {to:'urnammu',type:'mentor',note:'前辈法典启发'},
        {to:'rim_sin',type:'enemy',note:'吞并 Larsa 王国'},
      ] },
    { id:'rim_sin', name:'Rim-Sin 林辛', civ:'babylon', born:-1822, died:-1763, role:'Larsa 王',
      portrait:'🛡', desc:'统治 60 年的强大对手，被汉谟拉比击败。',
      inventions:[], relationships:[{to:'hammurabi',type:'enemy'}] },

    // ── 古埃及·新王国 (法老黄金时代) ──
    { id:'hatshepsut', name:'Hatshepsut 哈特谢普苏特', civ:'egypt_new', born:-1507, died:-1458, role:'女法老',
      portrait:'👸', desc:'埃及最成功女统治者。戴假胡子自称男性。派 Punt 远征。建 Deir el-Bahari 神庙。',
      inventions:['女法老制度','Punt 海上贸易','三层柱廊神庙'],
      relationships:[{to:'thutmose_iii',type:'family',note:'侄子/继子'}] },
    { id:'thutmose_iii', name:'Thutmose III 图特摩斯三世', civ:'egypt_new', born:-1481, died:-1425, role:'法老·军事天才',
      portrait:'⚔️', desc:'被称为"埃及的拿破仑"。Megiddo 战役击败联军。埃及版图最大。',
      inventions:['Megiddo 战役','埃及军事扩张顶峰'],
      relationships:[{to:'hatshepsut',type:'family'}] },
    { id:'akhenaten', name:'Akhenaten 阿肯那顿', civ:'egypt_new', born:-1380, died:-1336, role:'宗教革命法老',
      portrait:'☀️', desc:'推行历史第一次一神教改革，废所有神只崇拜 Aten。迁都 Amarna。死后被抹除。',
      inventions:['一神教 (Atenism)','Amarna 写实艺术风格','新首都'],
      relationships:[
        {to:'nefertiti',type:'family',note:'妻子'},
        {to:'tutankhamun',type:'family',note:'父亲 (DNA 证实)'},
      ] },
    { id:'nefertiti', name:'Nefertiti 奈费尔提蒂', civ:'egypt_new', born:-1370, died:-1330, role:'王后',
      portrait:'👑', desc:'Akhenaten 王后，其半身像是最美古埃及艺术。可能短暂统治过。',
      inventions:[], relationships:[{to:'akhenaten',type:'family'}] },
    { id:'tutankhamun', name:'Tutankhamun 图坦卡蒙', civ:'egypt_new', born:-1341, died:-1323, role:'少年法老',
      portrait:'🎭', desc:'9 岁登基，19 岁死。1922 年 Carter 发现完整未盗墓 — 黄金面具震撼世界。',
      inventions:['(本身贡献不大，但墓葬是 20 世纪最大考古发现)'],
      relationships:[{to:'akhenaten',type:'family'}] },
    { id:'ramesses_ii', name:'Ramesses II 拉美西斯二世', civ:'egypt_new', born:-1303, died:-1213, role:'"大帝"',
      portrait:'🦅', desc:'在位 66 年，活到 90 岁，100+ 孩子。建 Abu Simbel。Kadesh 战役与赫梯打平。',
      inventions:['Abu Simbel 巨像','Kadesh 战役','埃及-赫梯和约 (世界最早外交条约)'],
      relationships:[
        {to:'muwatalli_ii',type:'enemy',note:'Kadesh 战场对手'},
        {to:'hattusili_iii',type:'friend',note:'后来签订和约'},
      ] },
    { id:'ramesses_iii', name:'Ramesses III 拉美西斯三世', civ:'egypt_new', born:-1217, died:-1155, role:'最后伟大法老',
      portrait:'🛡', desc:'击退两次 Sea Peoples 入侵 (1177 BCE)。最后一位真正强大的法老。',
      inventions:['击败海上民族','Medinet Habu 神庙'], relationships:[] },

    // ── 商朝 ──
    { id:'wu_ding', name:'武丁 (Wu Ding)', civ:'shang', born:-1250, died:-1192, role:'商朝第 23 王',
      portrait:'⚱️', desc:'商朝鼎盛时期君主。60+ 年在位。征讨四方。妇好是他的王后。',
      inventions:['商朝鼎盛'],
      relationships:[{to:'fu_hao',type:'family',note:'王后'}] },
    { id:'fu_hao', name:'妇好 (Fu Hao)', civ:'shang', born:-1280, died:-1200, role:'王后·女将军',
      portrait:'🗡', desc:'中国最早有记载的女将军。曾率 13000 人征羌方。1976 完整墓出土 1928 件文物。',
      inventions:['女将军先例','大规模军事指挥'],
      relationships:[{to:'wu_ding',type:'family'}] },
    { id:'di_xin', name:'帝辛 (纣王)', civ:'shang', born:-1105, died:-1046, role:'商末代王',
      portrait:'👹', desc:'传统上被描绘为暴君。被周武王在牧野之战击败。考古证据较混合。',
      inventions:[],
      relationships:[{to:'zhou_wu_wang',type:'enemy',note:'牧野之战败给他'}] },
    { id:'zhou_wu_wang', name:'周武王', civ:'shang', born:-1100, died:-1043, role:'西周开国者',
      portrait:'⚔️', desc:'公元前 1046 牧野之战灭商，建立西周。"天命"政治哲学源此。',
      inventions:['西周王朝','天命思想'],
      relationships:[{to:'di_xin',type:'enemy'}] },

    // ── 米诺斯/迈锡尼 ──
    { id:'agamemnon_legend', name:'Agamemnon 阿伽门农 (传说)', civ:'mycenae', born:-1230, died:-1180, role:'迈锡尼联军统帅',
      portrait:'⚔️', desc:'传说中的特洛伊战争统帅。可能是真实国王的神话化。',
      inventions:['特洛伊战争 (传说)'], relationships:[] },

    // ── 赫梯 ──
    { id:'hattusili_i', name:'Hattusili I 哈图西里一世', civ:'hittite', born:-1700, died:-1620, role:'Old Hittite 创建者',
      portrait:'🛡', desc:'建立 Hattusa 首都，奠定 Hittite 帝国基础。',
      inventions:['Hattusa 首都','赫梯王朝'], relationships:[] },
    { id:'suppiluliuma_i', name:'Suppiluliuma I 苏皮鲁里乌玛一世', civ:'hittite', born:-1380, died:-1322, role:'Hittite 大王',
      portrait:'👑', desc:'扩张赫梯到帝国规模。其子 Zannanza 差点娶 Tutankhamun 寡妻成法老 (途中被杀)。',
      inventions:['赫梯帝国扩张'], relationships:[] },
    { id:'muwatalli_ii', name:'Muwatalli II 穆瓦塔利二世', civ:'hittite', born:-1330, died:-1272, role:'Kadesh 战役统帅',
      portrait:'🛡', desc:'1274 BCE 在 Kadesh 与 Ramesses II 打平。',
      inventions:[],
      relationships:[
        {to:'ramesses_ii',type:'enemy',note:'Kadesh 战场对手'},
        {to:'hattusili_iii',type:'family',note:'兄长'},
      ] },
    { id:'hattusili_iii', name:'Hattusili III 哈图西里三世', civ:'hittite', born:-1305, died:-1237, role:'与埃及签和约的赫梯王',
      portrait:'🤝', desc:'1259 BCE 与 Ramesses II 签世界最早外交条约。其王后 Puduhepa 是强势女政治家。',
      inventions:['世界最早外交条约'],
      relationships:[
        {to:'ramesses_ii',type:'friend',note:'和平条约签字方'},
        {to:'puduhepa',type:'family',note:'妻子'},
        {to:'muwatalli_ii',type:'family',note:'弟弟'},
      ] },
    { id:'puduhepa', name:'Puduhepa 普杜赫帕王后', civ:'hittite', born:-1290, died:-1215, role:'赫梯王后·政治家',
      portrait:'👸', desc:'与 Hattusili III 平起平坐。大量信件留下，证明她直接参与外交。',
      inventions:['女性政治家先例'],
      relationships:[{to:'hattusili_iii',type:'family'}] },

    // ── 现代考古学家 (重要发现者) ──
    { id:'champollion', name:'Champollion 商博良', civ:'modern', born:-1790, died:-1832, role:'破译象形文字 (1822)',
      portrait:'📜', desc:'通过 Rosetta 石碑破译古埃及象形文字，开启埃及学。',
      inventions:['象形文字破译','埃及学奠基'], relationships:[] },
    { id:'rawlinson', name:'Rawlinson 罗林森', civ:'modern', born:-1810, died:-1895, role:'破译楔形文字 (1857)',
      portrait:'📜', desc:'通过 Behistun 石刻破译楔形文字。',
      inventions:['楔形文字破译','亚述学奠基'], relationships:[] },
    { id:'woolley', name:'Woolley 伍利', civ:'modern', born:-1880, died:-1960, role:'发掘 Ur (1922-34)',
      portrait:'🏺', desc:'发现乌尔王陵 + 普阿比墓 + 洪水沉积层。',
      inventions:['乌尔王陵发现'], relationships:[] },
    { id:'carter', name:'Carter 卡特', civ:'modern', born:-1874, died:-1939, role:'发现 Tutankhamun 墓 (1922)',
      portrait:'🏺', desc:'KV62 墓未被盗，5000+ 文物震撼世界。',
      inventions:['图坦卡蒙墓发现'], relationships:[] },
    { id:'schliemann', name:'Schliemann 施里曼', civ:'modern', born:-1822, died:-1890, role:'发掘 Troy + Mycenae',
      portrait:'🏺', desc:'用《伊利亚特》当地图找到 Troy。证明荷马史诗有历史依据。',
      inventions:['Troy + Mycenae 重新发现'], relationships:[] },
    { id:'ventris', name:'Ventris 文特里斯', civ:'modern', born:-1922, died:-1956, role:'破译 Linear B (1952)',
      portrait:'📜', desc:'29 岁解开学界 50 年悬案，证明 Linear B 是希腊语祖先。',
      inventions:['Linear B 破译'], relationships:[] },
    { id:'wang_yirong', name:'王懿荣', civ:'modern', born:-1845, died:-1900, role:'发现甲骨文 (1899)',
      portrait:'📜', desc:'偶然在中药"龙骨"上认出甲骨文，开启商代研究。',
      inventions:['甲骨文发现'], relationships:[] },
  ],

  // ─────────────────────────────────────────────
  // 3. 重大事件 · 因果链
  //    每个事件: 年份, 文明, 类型, caused_by[], leads_to[]
  // ─────────────────────────────────────────────
  events: [
    { id:'evt_uruk_rise',     year:-3500, civ:'sumer',     type:'城市',   title:'Uruk 城市兴起',           caused_by:[], leads_to:['evt_cuneiform','evt_gilgamesh'] },
    { id:'evt_cuneiform',     year:-3300, civ:'sumer',     type:'文字',   title:'楔形文字诞生',            caused_by:['evt_uruk_rise'], leads_to:['evt_law_urnammu','evt_gilgamesh_epic'] },
    { id:'evt_narmer_unify',  year:-3100, civ:'egypt_old', type:'政治',   title:'Narmer 统一上下埃及',     caused_by:[], leads_to:['evt_djoser_pyramid','evt_hieroglyphs'] },
    { id:'evt_hieroglyphs',   year:-3200, civ:'egypt_old', type:'文字',   title:'象形文字成熟',            caused_by:['evt_narmer_unify'], leads_to:['evt_pyramid_texts'] },
    { id:'evt_djoser_pyramid',year:-2670, civ:'egypt_old', type:'建筑',   title:'Djoser 阶梯金字塔',       caused_by:['evt_narmer_unify'], leads_to:['evt_khufu_pyramid'] },
    { id:'evt_indus_cities',  year:-2600, civ:'indus',     type:'城市',   title:'Mohenjo-daro + Harappa 兴起', caused_by:[], leads_to:['evt_indus_collapse'] },
    { id:'evt_khufu_pyramid', year:-2560, civ:'egypt_old', type:'建筑',   title:'Khufu 大金字塔完工',       caused_by:['evt_djoser_pyramid'], leads_to:[] },
    { id:'evt_ur_royal_tomb', year:-2600, civ:'sumer',     type:'王权',   title:'Ur 王陵 + Puabi 殉葬',    caused_by:['evt_uruk_rise'], leads_to:[] },
    { id:'evt_sargon_empire', year:-2334, civ:'akkad',     type:'帝国',   title:'Sargon 建立第一帝国',     caused_by:['evt_uruk_rise'], leads_to:['evt_naramsin_god','evt_akkad_collapse'] },
    { id:'evt_naramsin_god',  year:-2254, civ:'akkad',     type:'宗教',   title:'Naram-Sin 自称为神',      caused_by:['evt_sargon_empire'], leads_to:[] },
    { id:'evt_42ka_drought',  year:-2200, civ:null,        type:'气候',   title:'4.2 ka 大干旱事件',       caused_by:[], leads_to:['evt_akkad_collapse','evt_old_kingdom_collapse','evt_indus_collapse'] },
    { id:'evt_akkad_collapse',year:-2154, civ:'akkad',     type:'崩溃',   title:'阿卡德帝国崩溃',          caused_by:['evt_42ka_drought'], leads_to:['evt_urnammu_law'] },
    { id:'evt_old_kingdom_collapse', year:-2181, civ:'egypt_old', type:'崩溃', title:'埃及古王国崩溃', caused_by:['evt_42ka_drought'], leads_to:[] },
    { id:'evt_urnammu_law',   year:-2100, civ:'sumer',     type:'法律',   title:'Ur-Nammu 法典 (最早成文法)', caused_by:['evt_akkad_collapse'], leads_to:['evt_hammurabi_law'] },
    { id:'evt_ur_zigurat',    year:-2100, civ:'sumer',     type:'建筑',   title:'Ur 大金字塔', caused_by:[], leads_to:[] },
    { id:'evt_gilgamesh_epic',year:-2100, civ:'sumer',     type:'文学',   title:'《吉尔伽美什史诗》成型',  caused_by:['evt_cuneiform'], leads_to:[] },
    { id:'evt_minoan_palaces',year:-2000, civ:'minoan',    type:'建筑',   title:'米诺斯宫殿时代开始',      caused_by:[], leads_to:['evt_thera_eruption'] },
    { id:'evt_indus_collapse',year:-1900, civ:'indus',     type:'崩溃',   title:'印度河文明衰落',          caused_by:['evt_42ka_drought'], leads_to:[] },
    { id:'evt_hammurabi_law', year:-1754, civ:'babylon',   type:'法律',   title:'汉谟拉比法典颁布',        caused_by:['evt_urnammu_law'], leads_to:[] },
    { id:'evt_thera_eruption',year:-1628, civ:'minoan',    type:'灾难',   title:'Thera/Santorini 火山大爆发', caused_by:[], leads_to:['evt_minoan_collapse'] },
    { id:'evt_shang_yinxu',   year:-1300, civ:'shang',     type:'城市',   title:'盘庚迁殷', caused_by:[], leads_to:['evt_oracle_bones','evt_fu_hao'] },
    { id:'evt_oracle_bones',  year:-1250, civ:'shang',     type:'文字',   title:'甲骨文系统化使用',        caused_by:['evt_shang_yinxu'], leads_to:[] },
    { id:'evt_fu_hao',        year:-1250, civ:'shang',     type:'人物',   title:'妇好率军征伐',            caused_by:['evt_shang_yinxu'], leads_to:[] },
    { id:'evt_minoan_collapse',year:-1450,civ:'minoan',    type:'崩溃',   title:'米诺斯被迈锡尼占领',      caused_by:['evt_thera_eruption'], leads_to:[] },
    { id:'evt_hatshepsut',    year:-1479, civ:'egypt_new', type:'政治',   title:'Hatshepsut 即位 (女法老)', caused_by:[], leads_to:[] },
    { id:'evt_akhenaten_rev', year:-1353, civ:'egypt_new', type:'宗教',   title:'Akhenaten 一神教改革',    caused_by:[], leads_to:['evt_amarna_collapse'] },
    { id:'evt_amarna_collapse',year:-1336,civ:'egypt_new', type:'宗教',   title:'Amarna 改革被抹除',       caused_by:['evt_akhenaten_rev'], leads_to:[] },
    { id:'evt_kadesh_battle', year:-1274, civ:'egypt_new', type:'战争',   title:'Kadesh 战役 (Ramesses II vs Hittite)', caused_by:[], leads_to:['evt_kadesh_treaty'] },
    { id:'evt_kadesh_treaty', year:-1259, civ:'egypt_new', type:'外交',   title:'埃及-赫梯和约 (最早外交条约)', caused_by:['evt_kadesh_battle'], leads_to:[] },
    { id:'evt_drought_1200',  year:-1250, civ:null,        type:'气候',   title:'地中海东部 150 年大旱开始', caused_by:[], leads_to:['evt_bronze_collapse'] },
    { id:'evt_ugarit_destroyed',year:-1190,civ:'collapse', type:'崩溃',   title:'Ugarit 被毁 (最后泥板)',  caused_by:['evt_sea_peoples'], leads_to:[] },
    { id:'evt_hittite_fall',  year:-1180, civ:'hittite',   type:'崩溃',   title:'Hattusa 烧毁，赫梯帝国瓦解', caused_by:['evt_drought_1200','evt_sea_peoples'], leads_to:[] },
    { id:'evt_sea_peoples',   year:-1177, civ:'collapse',  type:'入侵',   title:'Sea Peoples 入侵 (Ramesses III 击退)', caused_by:['evt_drought_1200'], leads_to:['evt_hittite_fall','evt_ugarit_destroyed'] },
    { id:'evt_bronze_collapse',year:-1177,civ:'collapse',  type:'崩溃',   title:'青铜时代大崩溃',          caused_by:['evt_drought_1200','evt_sea_peoples'], leads_to:['evt_iron_age','evt_alphabet','evt_greek_dark_age'] },
    { id:'evt_zhou_overthrow',year:-1046, civ:'shang',     type:'战争',   title:'牧野之战，周灭商',        caused_by:[], leads_to:[] },
    { id:'evt_greek_dark_age',year:-1100, civ:'mycenae',   type:'文化',   title:'希腊黑暗时代 (失字 300 年)', caused_by:['evt_bronze_collapse'], leads_to:['evt_alphabet'] },
    { id:'evt_alphabet',      year:-1050, civ:null,        type:'文字',   title:'腓尼基字母兴起 (识字大众化)', caused_by:['evt_bronze_collapse'], leads_to:[] },
    { id:'evt_iron_age',      year:-1100, civ:null,        type:'技术',   title:'铁器时代开始',            caused_by:['evt_bronze_collapse'], leads_to:[] },
  ],

  // ─────────────────────────────────────────────
  // 4. 文明对比卡 · 8 个标准维度
  //    每个维度横向比较所有 10 个文明
  // ─────────────────────────────────────────────
  comparison_dimensions: [
    { id:'writing',    name:'📜 文字', desc:'各文明的书写系统',
      values:{
        sumer:     '楔形文字 (3300 BCE)，世界最早，约 600 符号',
        egypt_old: '象形文字 (3200 BCE)，约 700 符号，宗教用',
        indus:     '印度河文字，约 400 符号，至今未破译',
        akkad:     '继承楔形文字，闪族语阿卡德语',
        babylon:   '阿卡德楔形文字',
        shang:     '甲骨文 (1300 BCE)，5000+ 字，汉字祖先',
        minoan:    'Linear A，至今未破译',
        mycenae:   'Linear B (1450 BCE)，希腊语最早形式',
        hittite:   'Hittite 楔形文字 + 象形文字两套',
        egypt_new: '象形文字延续 + Demotic 草书',
      } },
    { id:'government', name:'👑 政治制度',
      values:{
        sumer:     '城邦联盟 (Lugal 王 + 议会)',
        egypt_old: '法老神王 + 维齐尔宰相制',
        indus:     '分布式 (无王陵无宫殿，可能合议制)',
        akkad:     '中央集权帝国 (历史第一个)',
        babylon:   '王权 + 成文法典',
        shang:     '王 + 占卜祭司，征伐四方',
        minoan:    '可能祭司王 (神权)',
        mycenae:   '战士贵族 + Wanax 王',
        hittite:   '王 + 长老会议 (限制王权)',
        egypt_new: '法老神王，大祭司分权',
      } },
    { id:'religion', name:'🛐 宗教',
      values:{
        sumer:     '多神教 (Anu, Enlil, Inanna, Enki)',
        egypt_old: '多神 + 法老神化',
        indus:     '未知 (可能母神 + 自然崇拜)',
        akkad:     '继承苏美尔神 + Naram-Sin 自称神',
        babylon:   '多神 (Marduk 主神)',
        shang:     '祖先崇拜 + 上帝 + 占卜',
        minoan:    '母神 + 公牛崇拜',
        mycenae:   '希腊神最早形式 (Zeus, Poseidon)',
        hittite:   '"千神之国" (融合各民族神)',
        egypt_new: '多神 + Akhenaten 一神教 (短暂)',
      } },
    { id:'military', name:'⚔️ 军事',
      values:{
        sumer:     '步兵方阵 + 战车 (最早战车)',
        egypt_old: '征召农民军',
        indus:     '无大规模战争证据',
        akkad:     '专业军队 + 弓箭手',
        babylon:   '步兵 + 战车',
        shang:     '战车 + 青铜武器',
        minoan:    '无明显军事 (海上贸易)',
        mycenae:   '战士贵族 + 重装步兵',
        hittite:   '三人战车 (最先进) + 早期铁器',
        egypt_new: '战车军 + 海军 + 拉美西斯远征军',
      } },
    { id:'architecture', name:'🏛 建筑',
      values:{
        sumer:     '阶梯金字塔 (Ziggurat)，泥砖',
        egypt_old: '金字塔 (Khufu 146.5 米)，石造',
        indus:     '城市规划 + 下水道 + 标准砖',
        akkad:     '继承苏美尔风格',
        babylon:   '砖砌神庙 + 城墙',
        shang:     '夯土宫殿 + 王陵殉葬',
        minoan:    'Knossos 宫殿 (1300 房间) + 壁画',
        mycenae:   '巨石城堡 + 狮门 + 蜂窝墓',
        hittite:   'Hattusa 巨石防御 + 山地堡垒',
        egypt_new: 'Karnak 神庙 + Abu Simbel + 帝王谷',
      } },
    { id:'economy', name:'💰 经济',
      values:{
        sumer:     '灌溉农业 (大麦) + 长途贸易 (青金石、铜)',
        egypt_old: '尼罗河洪水农业 + 黄金贸易',
        indus:     '城市规划 + 海上贸易 (与 Mesopotamia)',
        akkad:     '帝国税收 + 标准化度量',
        babylon:   '银两本位 + 商业法律',
        shang:     '青铜礼器 + 玉器 + 贝币',
        minoan:    '海上贸易帝国 (橄榄油、葡萄酒)',
        mycenae:   '宫廷库存系统 (Linear B 记账)',
        hittite:   '铜锡贸易 + 农业基础',
        egypt_new: '金、奴隶、贸易、Punt 远征',
      } },
    { id:'science', name:'🔬 数学/科学',
      values:{
        sumer:     '60 进制 (今天 60 分钟) + 阴历 12 月',
        egypt_old: '几何 (金字塔精度) + 早期医学',
        indus:     '标准化度量衡',
        akkad:     '继承苏美尔数学',
        babylon:   'Plimpton 322 毕达哥拉斯三元组 + 高级天文',
        shang:     '日食月食记录 + 农历',
        minoan:    '未知 (Linear A 未解)',
        mycenae:   '行政算术',
        hittite:   '法律编纂 + 历史记录',
        egypt_new: '医学 (Ebers 莎草纸) + 工程',
      } },
    { id:'legacy', name:'🌍 留给今天的遗产',
      values:{
        sumer:     '城市概念、文字、60 进制、车轮、法律',
        egypt_old: '金字塔、象形文字、医学、法老形象',
        indus:     '城市规划标准化、未解之谜',
        akkad:     '"帝国"概念，后世所有帝国蓝本',
        babylon:   '成文法典、"以眼还眼"、数学',
        shang:     '汉字 (唯一延续至今的青铜文字)',
        minoan:    '希腊神话原型 + 迷宫 + 米诺陶',
        mycenae:   '希腊语祖先、荷马史诗原型',
        hittite:   '印欧语系最早证据、外交条约',
        egypt_new: '一神教萌芽、外交条约、Tutankhamun',
      } },
  ],
};

// 暴露给全局
if (typeof window !== 'undefined') {
  window.EARLY_CIV_EXPLORER = EARLY_CIV_EXPLORER;
  console.log('[EARLY_CIV_EXPLORER] loaded',
    EARLY_CIV_EXPLORER.civilizations.length, '文明,',
    EARLY_CIV_EXPLORER.people.length, '人物,',
    EARLY_CIV_EXPLORER.events.length, '事件,',
    EARLY_CIV_EXPLORER.comparison_dimensions.length, '对比维度');
}
