// 工业与现代世界(1750-1945) · 人物数据
const CLASSICAL_PEOPLE=[
  // 工业革命 (industrial)
  {id:"watt",n:"瓦特",e:"James Watt",c:"industrial",r:"thinker",d:"1736—1819",b:"改良蒸汽机(分离冷凝器),效率倍增,真正的工业革命引擎;功率单位'瓦特'以其命名。",rel:[{i:"arkwright",t:"工业革命同代"},{i:"stephenson",t:"蒸汽动力先驱"}]},
  {id:"arkwright",n:"阿克赖特",e:"Richard Arkwright",c:"industrial",r:"other",d:"1732—1792",b:"'工厂制度之父',建世界第一座水力纺纱厂,开创现代工厂管理。",rel:[{i:"watt",t:"工业革命同代"}]},
  {id:"stephenson",n:"斯蒂芬森",e:"George Stephenson",c:"industrial",r:"other",d:"1781—1848",b:"'铁路之父','火箭号'机车获胜,确立标准轨距。",rel:[{i:"watt",t:"承蒸汽动力"},{i:"brunel",t:"铁路时代同侪"}]},
  {id:"brunel",n:"布鲁内尔",e:"I.K. Brunel",c:"industrial",r:"other",d:"1806—1859",b:"维多利亚时代最伟大的工程师,大西方铁路、跨洋蒸汽船。",rel:[{i:"stephenson",t:"铁路工程同侪"}]},
  {id:"faraday",n:"法拉第",e:"Michael Faraday",c:"industrial",r:"thinker",d:"1791—1867",b:"发现电磁感应,发电机与电动机的理论基础。",rel:[{i:"edison",t:"启发电力时代"},{i:"tesla",t:"电学奠基"}]},
  {id:"edison",n:"爱迪生",e:"Thomas Edison",c:"industrial",r:"thinker",d:"1847—1931",b:"留声机、实用电灯、公共发电站;'电流之战'推直流电。",rel:[{i:"tesla",t:"电流之战对手"},{i:"faraday",t:"承其电学"}]},
  {id:"tesla",n:"特斯拉",e:"Nikola Tesla",c:"industrial",r:"thinker",d:"1856—1943",b:"交流电系统,可远距输电,'电流之战'最终胜出。",rel:[{i:"edison",t:"电流之战对手"}]},
  {id:"bell",n:"贝尔",e:"A.G. Bell",c:"industrial",r:"thinker",d:"1847—1922",b:"发明电话,远距即时通信。",rel:[]},
  {id:"benz",n:"卡尔·本茨",e:"Karl Benz",c:"industrial",r:"other",d:"1844—1929",b:"造出第一辆汽油汽车。",rel:[{i:"ford",t:"汽车工业先驱"}]},
  {id:"ford",n:"亨利·福特",e:"Henry Ford",c:"industrial",r:"other",d:"1863—1947",b:"T型车+流水线生产,让汽车进入大众,塑造现代工业生产。",rel:[{i:"benz",t:"承汽车发明"}]},
  {id:"wright",n:"莱特兄弟",e:"Wright Brothers",c:"industrial",r:"other",d:"1867—1948",b:"1903年首次动力飞行,开启航空时代。",rel:[]},
  {id:"darwin",n:"达尔文",e:"Charles Darwin",c:"industrial",r:"thinker",d:"1809—1882",b:"《物种起源》进化论,'物竞天择',深刻改变人类对自身的认识。",rel:[]},
  {id:"smith",n:"亚当·斯密",e:"Adam Smith",c:"industrial",r:"thinker",d:"1723—1790",b:"《国富论》自由市场理论,'看不见的手',现代经济学之父。",rel:[{i:"marx",t:"经济思想对立"}]},
  {id:"marx",n:"马克思",e:"Karl Marx",c:"industrial",r:"thinker",d:"1818—1883",b:"《资本论》《共产党宣言》,工业革命催生的社会主义,影响20世纪世界。",rel:[{i:"engels",t:"挚友合著"},{i:"smith",t:"批判其学说"}]},
  {id:"engels",n:"恩格斯",e:"Friedrich Engels",c:"industrial",r:"thinker",d:"1820—1895",b:"马克思挚友与合著者,《英国工人阶级状况》。",rel:[{i:"marx",t:"挚友合著"}]},
  {id:"pasteur",n:"巴斯德",e:"Louis Pasteur",c:"industrial",r:"thinker",d:"1822—1895",b:"微生物学之父,巴氏消毒、疫苗。",rel:[]},
  {id:"nobel",n:"诺贝尔",e:"Alfred Nobel",c:"industrial",r:"thinker",d:"1833—1896",b:"发明炸药,遗嘱设立诺贝尔奖。",rel:[]},
  {id:"curie",n:"居里夫人",e:"Marie Curie",c:"industrial",r:"thinker",d:"1867—1934",b:"发现镭与钋,两获诺贝尔奖,首位获诺奖的女性。",rel:[]},
  // 法国大革命与拿破仑 (french)
  {id:"voltaire",n:"伏尔泰",e:"Voltaire",c:"french",r:"thinker",d:"1694—1778",b:"启蒙思想家,批判教会与专制,捍卫言论自由。",rel:[{i:"rousseau",t:"启蒙同代"}]},
  {id:"rousseau",n:"卢梭",e:"Rousseau",c:"french",r:"thinker",d:"1712—1778",b:"《社会契约论》,'人生而自由','公意',深刻影响大革命。",rel:[{i:"voltaire",t:"启蒙同代"},{i:"robespierre",t:"思想被其奉行"}]},
  {id:"montesquieu",n:"孟德斯鸠",e:"Montesquieu",c:"french",r:"thinker",d:"1689—1755",b:"《论法的精神》,三权分立,影响近代宪政。",rel:[]},
  {id:"louis16",n:"路易十六",e:"Louis XVI",c:"french",r:"ruler",d:"1754—1793",b:"善良而优柔,法国大革命中1793年被送上断头台。",rel:[{i:"marie_ant",t:"王后"},{i:"robespierre",t:"被其处决"}]},
  {id:"marie_ant",n:"玛丽·安托瓦内特",e:"Marie Antoinette",c:"french",r:"other",d:"1755—1793",b:"奥地利公主、法国王后,1793年被处死。",rel:[{i:"louis16",t:"国王"}]},
  {id:"robespierre",n:"罗伯斯庇尔",e:"Robespierre",c:"french",r:"thinker",d:"1758—1794",b:"'不可腐蚀者',恐怖统治灵魂,热月政变被处死。",rel:[{i:"danton",t:"送其上断头台"},{i:"louis16",t:"推动处决"}]},
  {id:"danton",n:"丹东",e:"Danton",c:"french",r:"thinker",d:"1759—1794",b:"革命最激情的演说家,试图结束恐怖,被罗伯斯庇尔处决。",rel:[{i:"robespierre",t:"被其处决"}]},
  {id:"marat",n:"马拉",e:"Jean-Paul Marat",c:"french",r:"thinker",d:"1743—1793",b:"激进革命者,《人民之友报》主编,浴缸中被刺杀(《马拉之死》)。",rel:[]},
  {id:"napoleon",n:"拿破仑",e:"Napoleon",c:"french",r:"ruler",d:"1769—1821",b:"从科西嘉到法兰西皇帝,《拿破仑法典》、横扫欧洲,1815年滑铁卢落幕。",rel:[{i:"wellington",t:"滑铁卢对手"},{i:"nelson",t:"特拉法尔加对手"},{i:"metternich",t:"维也纳体系对手"}]},
  {id:"wellington",n:"威灵顿公爵",e:"Duke of Wellington",c:"french",r:"general",d:"1769—1852",b:"在西班牙与滑铁卢击败拿破仑。",rel:[{i:"napoleon",t:"击败之"}]},
  {id:"nelson",n:"纳尔逊",e:"Horatio Nelson",c:"french",r:"general",d:"1758—1805",b:"英国海军名将,特拉法尔加海战击败法西舰队、阵亡。",rel:[{i:"napoleon",t:"海上对手"}]},
  {id:"metternich",n:"梅特涅",e:"Metternich",c:"french",r:"thinker",d:"1773—1859",b:"奥地利首相,维也纳体系设计者,维持欧洲40年保守均势。",rel:[{i:"napoleon",t:"重建拿破仑后秩序"}]},
  // 帝国主义 (empire)
  {id:"victoria",n:"维多利亚女王",e:"Queen Victoria",c:"empire",r:"ruler",d:"1819—1901",b:"维多利亚时代大英帝国巅峰,1876年加冕'印度女皇'。",rel:[]},
  {id:"leopold2",n:"利奥波德二世",e:"Leopold II",c:"empire",r:"ruler",d:"1835—1909",b:"以'人道'之名残酷剥削刚果,约千万人死亡(《黑暗之心》背景)。",rel:[]},
  {id:"rhodes",n:"塞西尔·罗德斯",e:"Cecil Rhodes",c:"empire",r:"other",d:"1853—1902",b:"矿业巨头/帝国主义者,梦想'开罗到开普敦'铁路。",rel:[]},
  {id:"livingstone",n:"利文斯通",e:"David Livingstone",c:"empire",r:"other",d:"1813—1873",b:"苏格兰传教士、非洲探险家。",rel:[]},
  {id:"linzexu",n:"林则徐",e:"Lin Zexu",c:"empire",r:"thinker",d:"1785—1850",b:"1839年虎门销烟,引发第一次鸦片战争。",rel:[{i:"cixi",t:"晚清"}]},
  {id:"cixi",n:"慈禧太后",e:"Empress Dowager Cixi",c:"empire",r:"ruler",d:"1835—1908",b:"晚清实际最高统治者近半世纪,守旧误国。",rel:[{i:"lihongzhang",t:"重用"}]},
  {id:"lihongzhang",n:"李鸿章",e:"Li Hongzhang",c:"empire",r:"thinker",d:"1823—1901",b:"洋务运动领袖,签《马关条约》《辛丑条约》。",rel:[{i:"cixi",t:"效力"}]},
  {id:"hongxiuquan",n:"洪秀全",e:"Hong Xiuquan",c:"empire",r:"other",d:"1814—1864",b:"太平天国领袖,19世纪最血腥战争,约2000万人死。",rel:[]},
  // 意德统一 (unify)
  {id:"bismarck",n:"俾斯麦",e:"Otto von Bismarck",c:"unify",r:"thinker",d:"1815—1898",b:"'铁血宰相',三次王朝战争统一德国,1871年建德意志帝国。",rel:[{i:"wilhelm1",t:"辅佐"},{i:"wilhelm2",t:"被其罢免"}]},
  {id:"garibaldi",n:"加里波第",e:"Giuseppe Garibaldi",c:"unify",r:"general",d:"1807—1882",b:"'两个世界的英雄',千人远征推动意大利统一。",rel:[{i:"cavour",t:"统一伙伴"}]},
  {id:"cavour",n:"加富尔",e:"Cavour",c:"unify",r:"thinker",d:"1810—1861",b:"撒丁王国首相,意大利统一的'外交大脑'。",rel:[{i:"garibaldi",t:"统一伙伴"}]},
  {id:"wilhelm1",n:"威廉一世",e:"Wilhelm I",c:"unify",r:"ruler",d:"1797—1888",b:"第一位德意志皇帝,1871年于凡尔赛镜厅加冕。",rel:[{i:"bismarck",t:"重用"}]},
  // 明治日本 (meiji)
  {id:"meiji_emp",n:"明治天皇",e:"Emperor Meiji",c:"meiji",r:"ruler",d:"1852—1912",b:"明治维新,日本全面西化现代化,跻身列强。",rel:[{i:"ito",t:"股肱之臣"},{i:"saigo",t:"维新元勋"}]},
  {id:"saigo",n:"西乡隆盛",e:"Saigō Takamori",c:"meiji",r:"general",d:"1828—1877",b:"'维新三杰'之一,后领西南战争'最后的武士'。",rel:[{i:"okubo",t:"维新同志后对立"}]},
  {id:"okubo",n:"大久保利通",e:"Ōkubo Toshimichi",c:"meiji",r:"thinker",d:"1830—1878",b:"明治政府实际领导人,殖产兴业。",rel:[{i:"saigo",t:"维新同志后对立"}]},
  {id:"sakamoto",n:"坂本龙马",e:"Sakamoto Ryōma",c:"meiji",r:"other",d:"1836—1867",b:"促成萨长联盟,倒幕关键,遇刺;日本最受欢迎的历史人物之一。",rel:[]},
  {id:"ito",n:"伊藤博文",e:"Itō Hirobumi",c:"meiji",r:"thinker",d:"1841—1909",b:"四任首相,起草明治宪法,1909年被安重根刺杀。",rel:[{i:"meiji_emp",t:"效力"},{i:"bismarck",t:"学普鲁士宪法"}]},
  {id:"fukuzawa",n:"福泽谕吉",e:"Fukuzawa Yukichi",c:"meiji",r:"thinker",d:"1835—1901",b:"'日本的伏尔泰',《劝学篇》,创庆应义塾,'文明开化'。",rel:[]},
  {id:"togo",n:"东乡平八郎",e:"Tōgō Heihachirō",c:"meiji",r:"general",d:"1848—1934",b:"对马海战大败俄国舰队,亚洲首次在近代战争击败欧洲大国。",rel:[{i:"nelson",t:"学英国海军"}]},
  // 第一次世界大战 (ww1)
  {id:"franz_ferd",n:"弗朗茨·斐迪南",e:"Franz Ferdinand",c:"ww1",r:"ruler",d:"1863—1914",b:"奥匈皇储,1914年萨拉热窝遇刺,引爆一战。",rel:[{i:"princip",t:"被其刺杀"}]},
  {id:"princip",n:"普林西普",e:"Gavrilo Princip",c:"ww1",r:"other",d:"1894—1918",b:"塞尔维亚民族主义者,刺杀斐迪南,点燃一战。",rel:[{i:"franz_ferd",t:"刺杀对象"}]},
  {id:"wilhelm2",n:"威廉二世",e:"Wilhelm II",c:"ww1",r:"ruler",d:"1859—1941",b:"德国皇帝,罢免俾斯麦走'新路线',一战后退位流亡。",rel:[{i:"bismarck",t:"罢免之"}]},
  {id:"wilson",n:"威尔逊",e:"Woodrow Wilson",c:"ww1",r:"ruler",d:"1856—1924",b:"美国总统,'十四点计划'、倡建国际联盟。",rel:[]},
  {id:"clemenceau",n:"克列孟梭",e:"Clemenceau",c:"ww1",r:"ruler",d:"1841—1929",b:"法国'老虎'总理,主导凡尔赛对德苛刻条款。",rel:[]},
  {id:"ataturk",n:"凯末尔",e:"Atatürk",c:"ww1",r:"general",d:"1881—1938",b:"加利波利的奥斯曼英雄,后建立土耳其共和国、世俗化改革。",rel:[]},
  {id:"nicholas2",n:"尼古拉二世",e:"Nicholas II",c:"ww1",r:"ruler",d:"1868—1918",b:"末代沙皇,一战中崩溃,1917年退位,1918年被处决。",rel:[]},
  // 第二次世界大战 (ww2)
  {id:"hitler",n:"希特勒",e:"Adolf Hitler",c:"ww2",r:"ruler",d:"1889—1945",b:"纳粹德国元首,发动二战、制造大屠杀,1945年自杀。",rel:[{i:"mussolini",t:"轴心盟友"},{i:"churchill",t:"宿敌"},{i:"stalin",t:"先盟后战"}]},
  {id:"mussolini",n:"墨索里尼",e:"Mussolini",c:"ww2",r:"ruler",d:"1883—1945",b:"意大利法西斯领袖,1945年被游击队处决。",rel:[{i:"hitler",t:"轴心盟友"}]},
  {id:"tojo",n:"东条英机",e:"Tōjō Hideki",c:"ww2",r:"ruler",d:"1884—1948",b:"日本战时首相,主导对美开战,战后被判绞刑。",rel:[]},
  {id:"churchill",n:"丘吉尔",e:"Winston Churchill",c:"ww2",r:"ruler",d:"1874—1965",b:"英国战时首相,'热血、辛劳、眼泪与汗水',最伟大的战时演说家。",rel:[{i:"roosevelt",t:"同盟"},{i:"hitler",t:"宿敌"}]},
  {id:"roosevelt",n:"罗斯福",e:"F.D. Roosevelt",c:"ww2",r:"ruler",d:"1882—1945",b:"美国总统,新政与战时领导,四次当选,1945年去世。",rel:[{i:"churchill",t:"同盟"},{i:"stalin",t:"同盟"}]},
  {id:"stalin",n:"斯大林",e:"Joseph Stalin",c:"ww2",r:"ruler",d:"1878—1953",b:"苏联领导人,大清洗、卫国战争,组织惊人反击击败纳粹。",rel:[{i:"hitler",t:"先盟后战"},{i:"churchill",t:"同盟"}]},
  {id:"degaulle",n:"戴高乐",e:"Charles de Gaulle",c:"ww2",r:"general",d:"1890—1970",b:"'自由法国'领袖,'法国输了战役但没输掉战争'。",rel:[]},
  {id:"chiang",n:"蒋介石",e:"Chiang Kai-shek",c:"ww2",r:"ruler",d:"1887—1975",b:"中国国民政府领袖,领导抗日战争。",rel:[{i:"maozedong",t:"国共合作与内战"}]},
  {id:"maozedong",n:"毛泽东",e:"Mao Zedong",c:"ww2",r:"ruler",d:"1893—1976",b:"中共领袖,抗战期间国共合作,1949年建立新中国。",rel:[{i:"chiang",t:"国共合作与内战"}]},
  {id:"truman",n:"杜鲁门",e:"Harry Truman",c:"ww2",r:"ruler",d:"1884—1972",b:"罗斯福去世后继任,下令投掷原子弹。",rel:[{i:"oppenheimer",t:"批准用原子弹"}]},
  {id:"eisenhower",n:"艾森豪威尔",e:"Eisenhower",c:"ww2",r:"general",d:"1890—1969",b:"盟军欧洲最高司令,诺曼底登陆总指挥。",rel:[]},
  {id:"zhukov",n:"朱可夫",e:"Georgy Zhukov",c:"ww2",r:"general",d:"1896—1974",b:"苏联最伟大的将领,莫斯科/斯大林格勒/柏林。",rel:[{i:"stalin",t:"麾下统帅"}]},
  {id:"rommel",n:"隆美尔",e:"Erwin Rommel",c:"ww2",r:"general",d:"1891—1944",b:"'沙漠之狐',北非军团;牵连刺杀希特勒被迫自尽。",rel:[]},
  {id:"yamamoto",n:"山本五十六",e:"Yamamoto Isoroku",c:"ww2",r:"general",d:"1884—1943",b:"策划珍珠港,'我担心只是唤醒了沉睡的巨人',1943年被击落。",rel:[]},
  {id:"oppenheimer",n:"奥本海默",e:"Oppenheimer",c:"ww2",r:"thinker",d:"1904—1967",b:"曼哈顿计划科学总监,'我成了死神,世界的毁灭者'。",rel:[{i:"einstein",t:"原子弹研究"},{i:"truman",t:"为其造弹"}]},
  {id:"einstein",n:"爱因斯坦",e:"Albert Einstein",c:"ww2",r:"thinker",d:"1879—1955",b:"相对论;1939年致信罗斯福促成原子弹研究。",rel:[{i:"oppenheimer",t:"原子能"}]},
  {id:"anne_frank",n:"安妮·弗兰克",e:"Anne Frank",c:"ww2",r:"other",d:"1929—1945",b:"《安妮日记》,大屠杀最著名的个人记录。",rel:[]},
];
const CLASSICAL_ICON = {
  watt:'⚙️',arkwright:'🧵',stephenson:'🚂',brunel:'🌉',faraday:'🧲',edison:'💡',tesla:'⚡',bell:'☎️',benz:'🚗',ford:'🏭',wright:'✈️',darwin:'🐢',smith:'💰',marx:'📕',engels:'📗',pasteur:'🧫',nobel:'🧨',curie:'☢️',
  voltaire:'🪶',rousseau:'📜',montesquieu:'⚖️',louis16:'👑',marie_ant:'👑',robespierre:'🗡️',danton:'📣',marat:'🛁',napoleon:'🎩',wellington:'🎖️',nelson:'⚓',metternich:'🤝',
  victoria:'👑',leopold2:'🩸',rhodes:'💎',livingstone:'🧭',linzexu:'🚭',cixi:'👑',lihongzhang:'📜',hongxiuquan:'☯️',
  bismarck:'🩸',garibaldi:'🗡️',cavour:'🧠',wilhelm1:'👑',
  meiji_emp:'👑',saigo:'🗡️',okubo:'📜',sakamoto:'🌊',ito:'📜',fukuzawa:'📖',togo:'⚓',
  franz_ferd:'👑',princip:'🔫',wilhelm2:'👑',wilson:'🕊️',clemenceau:'🐯',ataturk:'🌙',nicholas2:'👑',
  hitler:'⚔️',mussolini:'⚔️',tojo:'⚔️',churchill:'🎩',roosevelt:'♿',stalin:'⭐',degaulle:'🇫🇷',chiang:'🎖️',maozedong:'⭐',truman:'💣',eisenhower:'🎖️',zhukov:'⭐',rommel:'🦊',yamamoto:'⚓',oppenheimer:'☢️',einstein:'🧠',anne_frank:'📔',
};
const ROLE_ICON_FALLBACK = {ruler:'👑',general:'⚔️',thinker:'📜',religious:'✝️',other:'🔹'};
function personIconOf(p){ if(!p) return '👤'; const id=typeof p==='string'?p:p.id; if(CLASSICAL_ICON[id])return CLASSICAL_ICON[id]; const role=typeof p==='object'?p.r:null; return ROLE_ICON_FALLBACK[role]||'👤'; }
if(typeof window!=='undefined'){window.CLASSICAL_ICON=CLASSICAL_ICON;window.personIconOf=personIconOf;}
